// packages/client/src/ui/shell/connection/ConnectionStatusBar.tsx
import { ConnectionStatus } from "@rtc/domain";
import { useHooks } from "../../hooks/HooksProvider";

const statusLabel: Record<ConnectionStatus, string> = {
  [ConnectionStatus.CONNECTING]: "Connecting...",
  [ConnectionStatus.CONNECTED]: "Connected",
  [ConnectionStatus.DISCONNECTED]: "Disconnected",
  [ConnectionStatus.IDLE_DISCONNECTED]: "Idle",
  [ConnectionStatus.OFFLINE_DISCONNECTED]: "Offline",
};

const statusColor: Record<ConnectionStatus, string> = {
  [ConnectionStatus.CONNECTING]: "var(--status-connecting)",
  [ConnectionStatus.CONNECTED]: "var(--status-connected)",
  [ConnectionStatus.DISCONNECTED]: "var(--status-disconnected)",
  [ConnectionStatus.IDLE_DISCONNECTED]: "var(--status-disconnected)",
  [ConnectionStatus.OFFLINE_DISCONNECTED]: "var(--status-disconnected)",
};

export function ConnectionStatusBar() {
  const { useConnectionStatus } = useHooks();
  const status = useConnectionStatus();

  return (
    <div
      data-testid="connection-status"
      style={{
        display: "flex",
        alignItems: "center",
        gap: 6,
        fontSize: 12,
        color: "var(--text-secondary)",
      }}
    >
      <span
        style={{
          width: 8,
          height: 8,
          borderRadius: "50%",
          backgroundColor: statusColor[status],
          display: "inline-block",
        }}
      />
      <span>{statusLabel[status]}</span>
    </div>
  );
}

// packages/client-solid/src/ui/shell/connection/ConnectionStatusBar.tsx
import type { JSX } from "solid-js";

import { ConnectionStatus } from "@rtc/domain";
import { useViewModel } from "@rtc/solid-bindings";

import styles from "./ConnectionStatusBar.module.css";

export function ConnectionStatusBar(): JSX.Element {
  const { useConnectionStatus } = useViewModel();
  const status = useConnectionStatus();

  return (
    <div data-testid="connection-status" class={styles.statusBar}>
      <span data-status={status()} class={styles.dot} />
      <span data-status={status()} class={styles.label}>
        {statusLabel[status()]}
      </span>
    </div>
  );
}

// Footer collapses IDLE_DISCONNECTED and OFFLINE_DISCONNECTED to "Disconnected":
// the distinct idle/offline wording lives in ConnectionOverlay, not the footer.
// Provenance: original App/Footer/StatusButton/StatusButton.tsx:8-19.
const statusLabel: Record<ConnectionStatus, string> = {
  [ConnectionStatus.CONNECTING]: "Connecting...",
  [ConnectionStatus.CONNECTED]: "Connected",
  [ConnectionStatus.DISCONNECTED]: "Disconnected",
  [ConnectionStatus.IDLE_DISCONNECTED]: "Disconnected",
  [ConnectionStatus.OFFLINE_DISCONNECTED]: "Disconnected",
};
