// packages/client-prototype/src/admin/Latency/LatencyHistogram.tsx
import type { CSSProperties, ReactElement } from "react";

import styles from "#/admin/Latency/LatencyHistogram.module.css";
import type { LatBar } from "#/admin/types";

export interface LatencyHistogramProps {
  bars: LatBar[];
}

// PROTO L701-706: latency-distribution histogram — one bar per bucket, height
// via a --bar-h custom property, accent bucket flagged with data-accent.
export function LatencyHistogram(props: LatencyHistogramProps): ReactElement {
  const { bars } = props;

  return (
    <div className={styles.card}>
      <div className={styles.head}>
        <span className={styles.title}>LATENCY DISTRIBUTION</span>
        <span className={styles.sub}>ms</span>
      </div>
      <div className={styles.bars}>
        {bars.map((bar) => {
          const barStyle = { "--bar-h": `${bar.heightPct}%` } as CSSProperties;
          return (
            <div className={styles.col} key={bar.label}>
              <div
                className={styles.bar}
                data-accent={String(bar.accent)}
                style={barStyle}
              />
              <span className={styles.tick}>{bar.label}</span>
            </div>
          );
        })}
      </div>
    </div>
  );
}

// packages/client-solid/src/ui/admin/LatencyHistogram.tsx
import type { JSX } from "solid-js";
import { createMemo, For, Show } from "solid-js";

import { type LatBarVm, latencyBuckets } from "@rtc/core-logic";
import { useViewModel } from "@rtc/solid-bindings";

import styles from "./LatencyHistogram.module.css";

/**
 * Latency-distribution histogram — 6 fixed buckets (ported from PROTO
 * Latency/LatencyHistogram.tsx), each bar's height driven by a --bar-h custom
 * property computed by the shared latencyBuckets vm (core-logic) from the
 * live latency window; the modal (highest-count) bucket is flagged via
 * data-accent.
 */
export function LatencyHistogram(): JSX.Element {
  const { useMetrics } = useViewModel();
  const { latency } = useMetrics();

  const bars = createMemo((): readonly LatBarVm[] => {
    return latencyBuckets(latency());
  });

  return (
    <div data-testid="admin-latency-histogram" class={styles.card}>
      <div class={styles.head}>
        <span class={styles.title}>LATENCY DISTRIBUTION</span>
        <span class={styles.sub}>ms</span>
      </div>
      <Show
        when={latency().length > 0}
        fallback={<div class={styles.empty}>NO DATA</div>}
      >
        <div class={styles.bars}>
          <For each={bars()}>
            {(bar: LatBarVm) => {
              return (
                <div class={styles.col}>
                  <div
                    class={styles.bar}
                    data-accent={String(bar.accent)}
                    // eslint-disable-next-line no-restricted-syntax -- runtime bar height via CSS custom property; static CSS can't express a per-bucket value
                    style={{ "--bar-h": `${bar.heightPct}%` }}
                  />
                  <span class={styles.tick}>{bar.label}</span>
                </div>
              );
            }}
          </For>
        </div>
      </Show>
    </div>
  );
}
