// packages/client-react/src/ui/shell/layout/engine/PanelHeadControls.tsx
import type { ReactElement } from "react";

import type { PanelId } from "@rtc/core-api";

import styles from "./PanelHead.module.css";

/** The header's RIGHT half: the collapse ("—") and maximize (⛶ / ⧉ once
 * maximized) controls, plus the optional pop-out (↗) and close (✕) slots.
 * `maximizable: false` hides only the maximize control — the panel still
 * strips when a sibling maximizes (spec'd on PanelSpec). */
export function PanelHeadControls({
  panelId,
  title,
  maximizable,
  maximizedHere,
  poppedHere,
  floatingHere,
  attachedHere,
  onCollapse,
  onMaximize,
  onRestore,
  onPopout,
  onDetach,
  onFloat,
  onClose,
}: PanelHeadControlsProps): ReactElement {
  // While the panel lives in a pop-out window the geometry intents have no
  // meaning for its group (parked in another document) — every control
  // greys out until the window closes and the panel docks home.
  const popped = poppedHere === true;
  // While the panel is floating, collapse and maximize have no meaning for
  // its group (a box over the grid, not a grid member) — both controls are
  // HIDDEN outright rather than greyed, unlike the pop-out precedent above.
  const floating = floatingHere === true;
  return (
    <div className={styles.panelControls}>
      {onPopout !== undefined ? (
        <button
          type="button"
          data-testid={`panel-${panelId}-popout`}
          className={styles.panelControl}
          aria-label={`Pop out ${title}`}
          title={`Pop out ${title}`}
          disabled={popped}
          aria-disabled={popped}
          onClick={onPopout}
        >
          ↗
        </button>
      ) : null}
      {attachedHere && onDetach !== undefined ? (
        <button
          type="button"
          data-testid={`panel-${panelId}-detach`}
          className={styles.panelControl}
          aria-label={`Detach ${title}`}
          title={`Detach ${title}`}
          disabled={popped}
          aria-disabled={popped}
          onClick={onDetach}
        >
          ⇱
        </button>
      ) : null}
      {onFloat !== undefined ? (
        <button
          type="button"
          data-testid={`panel-${panelId}-float`}
          className={styles.panelControl}
          aria-label={floating ? `Dock ${title}` : `Float ${title}`}
          title={floating ? `Dock ${title}` : `Float ${title}`}
          disabled={popped}
          aria-disabled={popped}
          onClick={onFloat}
        >
          {floating ? "⚓" : "◱"}
        </button>
      ) : null}
      {floating ? null : (
        <button
          type="button"
          data-testid={`panel-${panelId}-collapse`}
          className={styles.panelControl}
          aria-label={`Collapse ${title}`}
          title={`Collapse ${title}`}
          disabled={popped}
          aria-disabled={popped}
          onClick={onCollapse}
        >
          —
        </button>
      )}
      {maximizable && !floating ? (
        <button
          type="button"
          data-testid={`panel-${panelId}-maximize`}
          className={styles.panelControl}
          aria-label={maximizedHere ? `Restore ${title}` : `Maximize ${title}`}
          title={maximizedHere ? `Restore ${title}` : `Maximize ${title}`}
          disabled={popped}
          aria-disabled={popped}
          onClick={maximizedHere ? onRestore : onMaximize}
        >
          {maximizedHere ? "⧉" : "⛶"}
        </button>
      ) : null}
      {onClose !== undefined ? (
        <button
          type="button"
          data-testid={`panel-${panelId}-close`}
          className={styles.panelControl}
          aria-label={`Close ${title}`}
          title={`Close ${title}`}
          disabled={popped}
          aria-disabled={popped}
          onClick={onClose}
        >
          ✕
        </button>
      ) : null}
    </div>
  );
}

export interface PanelHeadControlsProps {
  panelId: PanelId;
  title: string;
  maximizable: boolean;
  maximizedHere: boolean;
  /** True while this panel lives in a pop-out window: collapse, maximize and
   * the pop-out control itself grey out — the geometry intents have no
   * meaning for a group parked in another document. */
  poppedHere?: boolean;
  /** True while this panel's group is floating over the grid: collapse and
   * maximize are HIDDEN outright (not merely greyed, unlike `poppedHere`) —
   * a floating box is not a grid member, so those geometry intents have no
   * target. */
  floatingHere?: boolean;
  /** True while this panel's floating window holds other panels too (an
   * attached cluster, float magnets): the detach control renders. */
  attachedHere?: boolean;
  // Slots (property syntax): the header never knows what an engine attaches
  // — see docs/handler-naming.md's slot-vs-handler doctrine.
  onCollapse: () => void;
  onMaximize: () => void;
  onRestore: () => void;
  /** Pops the panel out into its own browser window. Optional slot — only
   * the dockview bridge attaches it (the `mountActions` engine-gating
   * idiom): in-house and RN heads render no pop-out control, zero fan-out. */
  onPopout?: () => void;
  /** Floats the panel's group as a box over the grid, or returns it home once
   * already floating — same optional-slot idiom as `onPopout`, attached only
   * by the dockview bridge. */
  onFloat?: () => void;
  /** Pulls the panel out of its attached cluster into its own float. Optional
   * slot, attached only by the dockview bridge, like `onFloat`. */
  onDetach?: () => void;
  /** Closes the panel outright. Optional slot — only the dockview bridge
   * attaches it, and only for a dynamically opened chart instance (a static
   * panel closes through the View menu instead); absent, the head renders no
   * close control and its markup is unchanged. */
  onClose?: () => void;
}

// packages/client-solid/src/ui/shell/layout/engine/PanelHeadControls.tsx
import { type JSX, Show } from "solid-js";

import type { PanelId } from "@rtc/core-api";

import styles from "./PanelHead.module.css";

/** The header's RIGHT half: the collapse ("—") and maximize (⛶ / ⧉ once
 * maximized) controls, plus the optional pop-out (↗) and close (✕) slots.
 * `maximizable: false` hides only the maximize control — the panel still
 * strips when a sibling maximizes (spec'd on PanelSpec).
 * Shared by both layout engines (the in-house `.panelHeader`, dockview's
 * group actions slot); styled by PanelHead.module.css alongside
 * PanelHeadSlot and PanelStrip. */
export function PanelHeadControls(props: PanelHeadControlsProps): JSX.Element {
  function maximizeLabel(): string {
    return props.maximizedHere
      ? `Restore ${props.title}`
      : `Maximize ${props.title}`;
  }

  // While the panel lives in a pop-out window the geometry intents have no
  // meaning for its group (parked in another document) — every control
  // greys out until the window closes and the panel docks home.
  function popped(): boolean {
    return props.poppedHere === true;
  }

  // While the panel is floating, collapse and maximize have no meaning for
  // its group (a box over the grid, not a grid member) — both controls are
  // HIDDEN outright rather than greyed, unlike the pop-out precedent above.
  function floating(): boolean {
    return props.floatingHere === true;
  }

  function collapsePanel(): void {
    props.onCollapse();
  }

  function maximizeOrRestorePanel(): void {
    props.maximizedHere ? props.onRestore() : props.onMaximize();
  }

  function popoutPanel(): void {
    props.onPopout?.();
  }

  function detachPanel(): void {
    props.onDetach?.();
  }

  function floatOrDockPanel(): void {
    props.onFloat?.();
  }

  function closePanel(): void {
    props.onClose?.();
  }

  return (
    <div class={styles.panelControls}>
      <Show when={props.onPopout !== undefined}>
        <button
          type="button"
          data-testid={`panel-${props.panelId}-popout`}
          class={styles.panelControl}
          aria-label={`Pop out ${props.title}`}
          title={`Pop out ${props.title}`}
          disabled={popped()}
          aria-disabled={popped()}
          onClick={popoutPanel}
        >
          ↗
        </button>
      </Show>
      <Show when={props.attachedHere === true && props.onDetach !== undefined}>
        <button
          type="button"
          data-testid={`panel-${props.panelId}-detach`}
          class={styles.panelControl}
          aria-label={`Detach ${props.title}`}
          title={`Detach ${props.title}`}
          disabled={popped()}
          aria-disabled={popped()}
          onClick={detachPanel}
        >
          ⇱
        </button>
      </Show>
      <Show when={props.onFloat !== undefined}>
        <button
          type="button"
          data-testid={`panel-${props.panelId}-float`}
          class={styles.panelControl}
          aria-label={
            floating() ? `Dock ${props.title}` : `Float ${props.title}`
          }
          title={floating() ? `Dock ${props.title}` : `Float ${props.title}`}
          disabled={popped()}
          aria-disabled={popped()}
          onClick={floatOrDockPanel}
        >
          {floating() ? "⚓" : "◱"}
        </button>
      </Show>
      <Show when={!floating()}>
        <button
          type="button"
          data-testid={`panel-${props.panelId}-collapse`}
          class={styles.panelControl}
          aria-label={`Collapse ${props.title}`}
          title={`Collapse ${props.title}`}
          disabled={popped()}
          aria-disabled={popped()}
          onClick={collapsePanel}
        >
          —
        </button>
      </Show>
      <Show when={props.maximizable && !floating()}>
        <button
          type="button"
          data-testid={`panel-${props.panelId}-maximize`}
          class={styles.panelControl}
          aria-label={maximizeLabel()}
          title={maximizeLabel()}
          disabled={popped()}
          aria-disabled={popped()}
          onClick={maximizeOrRestorePanel}
        >
          {props.maximizedHere ? "⧉" : "⛶"}
        </button>
      </Show>
      <Show when={props.onClose !== undefined}>
        <button
          type="button"
          data-testid={`panel-${props.panelId}-close`}
          class={styles.panelControl}
          aria-label={`Close ${props.title}`}
          title={`Close ${props.title}`}
          disabled={popped()}
          aria-disabled={popped()}
          onClick={closePanel}
        >
          ✕
        </button>
      </Show>
    </div>
  );
}

export interface PanelHeadControlsProps {
  panelId: PanelId;
  title: string;
  maximizable: boolean;
  maximizedHere: boolean;
  /** True while this panel lives in a pop-out window: collapse, maximize and
   * the pop-out control itself grey out — the geometry intents have no
   * meaning for a group parked in another document. */
  poppedHere?: boolean;
  /** True while this panel's group is floating over the grid: collapse and
   * maximize are HIDDEN outright (not merely greyed, unlike `poppedHere`) —
   * a floating box is not a grid member, so those geometry intents have no
   * target. */
  floatingHere?: boolean;
  /** True while this panel's floating window holds other panels too (an
   * attached cluster, float magnets): the detach control renders. */
  attachedHere?: boolean;
  // Slots (property syntax): the header never knows what an engine attaches
  // — see docs/handler-naming.md's slot-vs-handler doctrine.
  onCollapse: () => void;
  onMaximize: () => void;
  onRestore: () => void;
  /** Pops the panel out into its own browser window. Optional slot — only
   * the dockview bridge attaches it (the `mountActions` engine-gating
   * idiom): in-house and RN heads render no pop-out control, zero fan-out. */
  onPopout?: () => void;
  /** Floats the panel's group as a box over the grid, or returns it home once
   * already floating — same optional-slot idiom as `onPopout`, attached only
   * by the dockview bridge. */
  onFloat?: () => void;
  /** Pulls the panel out of its attached cluster into its own float. Optional
   * slot, attached only by the dockview bridge, like `onFloat`. */
  onDetach?: () => void;
  /** Closes the panel outright. Optional slot — only the dockview bridge
   * attaches it, and only for a dynamically opened chart instance (a static
   * panel closes through the View menu instead); absent, the head renders no
   * close control and its markup is unchanged. */
  onClose?: () => void;
}
