// packages/client-prototype/src/credit/Rfqs/EmptyRfqs.tsx
import type { ReactElement } from "react";

import styles from "#/credit/Rfqs/EmptyRfqs.module.css";

// PROTO L562: the dashed-border placeholder shown when no RFQs match the
// active filter.
export function EmptyRfqs(): ReactElement {
  return (
    <div className={styles.empty}>
      <div className={styles.glyph}>◇</div>
      <div className={styles.title}>No RFQs to show</div>
      <div className={styles.hint}>Create one with the New RFQ form</div>
    </div>
  );
}

// packages/client-solid/src/ui/credit/rfqs/EmptyRfqs.tsx
import type { JSX } from "solid-js";

import styles from "./EmptyRfqs.module.css";

/** PROTO Rfqs/EmptyRfqs.tsx: the dashed-border placeholder shown when no RFQs
 * match the active filter. */
export function EmptyRfqs(): JSX.Element {
  return (
    <div class={styles.empty}>
      <div class={styles.glyph}>◇</div>
      <div class={styles.title}>No RFQs to show</div>
      <div class={styles.hint}>Create one with the New RFQ form</div>
    </div>
  );
}
