// packages/client-react/src/ui/fx/blotter/QuickFilter.tsx
import styles from "./QuickFilter.module.css";

interface QuickFilterProps {
  value: string;
  onChange: (value: string) => void;
}

export function QuickFilter({ value, onChange }: QuickFilterProps) {
  return (
    <input
      data-testid="quick-filter"
      type="text"
      value={value}
      onChange={(e) => {
        return onChange(e.target.value);
      }}
      placeholder="Quick filter..."
      className={styles.input}
    />
  );
}

// packages/client-solid/src/ui/fx/blotter/QuickFilter.tsx
import type { JSX } from "solid-js";

import styles from "./QuickFilter.module.css";

export function QuickFilter(props: QuickFilterProps): JSX.Element {
  return (
    <input
      data-testid="quick-filter"
      type="text"
      value={props.value}
      onChange={(e: InputChangeEvent): void => {
        props.onChange(e.currentTarget.value);
      }}
      placeholder="Quick filter..."
      class={styles.input}
    />
  );
}

interface QuickFilterProps {
  value: string;
  onChange: (value: string) => void;
}

type InputChangeEvent = Event & { currentTarget: HTMLInputElement };
