// packages/client/src/blotter/quick-filter.tsx
interface QuickFilterProps {
  value: string;
  onChange: (value: string) => void;
}

export function QuickFilter({ value, onChange }: QuickFilterProps) {
  return (
    <input
      data-testid="quick-filter"
      type="text"
      value={value}
      onChange={(e) => onChange(e.target.value)}
      placeholder="Quick filter..."
      style={{
        padding: "4px 8px",
        fontSize: 12,
        border: "1px solid var(--border-primary)",
        borderRadius: 3,
        backgroundColor: "transparent",
        color: "var(--text-primary)",
        outline: "none",
        width: 200,
      }}
    />
  );
}

// packages/client-solid/src/ui/fx/blotter/QuickFilter.tsx
import type { JSX } from "solid-js";

import styles from "./QuickFilter.module.css";

export function QuickFilter(props: QuickFilterProps): JSX.Element {
  return (
    <input
      data-testid="quick-filter"
      type="text"
      value={props.value}
      onChange={(e: InputChangeEvent): void => {
        props.onChange(e.currentTarget.value);
      }}
      placeholder="Quick filter..."
      class={styles.input}
    />
  );
}

interface QuickFilterProps {
  value: string;
  onChange: (value: string) => void;
}

type InputChangeEvent = Event & { currentTarget: HTMLInputElement };
