// packages/client-solid/src/ui/shell/lock/LockScreen.tsx
import { type Accessor, createSignal, type JSX, Show } from "solid-js";

import type { SessionUser } from "@rtc/domain";
import { useViewModel } from "@rtc/solid-bindings";

import { HandshakeConsole } from "../auth/wait/HandshakeConsole";
import { ReactorRings } from "../auth/wait/ReactorRings";
import { ReactorWait } from "../auth/wait/ReactorWait";
import { HudLogo } from "../logo/HudLogo";
import { BiometricChannel } from "./BiometricChannel";
import { BiometricDots } from "./BiometricDots";

import waitStyles from "../auth/wait/authWait.module.css";
import styles from "./LockScreen.module.css";

/**
 * Full-screen session-lock overlay (prototype Reactive Trader.dc.html:76-91).
 * Renders nothing unless the session is locked; while locked it shows the
 * operator identity and a password-gated AUTHENTICATE control that
 * re-authenticates (unlock) against the real credentials seam. Dumb
 * component: all state arrives through the `useAuth` hook seam; the typed
 * password lives in local component state only and is never logged.
 */
export function LockScreen(): JSX.Element {
  const { useAuth } = useViewModel();
  const { state, unlock } = useAuth();
  const [password, setPassword] = createSignal("");

  function submitUnlock(event: SubmitEvent): void {
    event.preventDefault();
    unlock(password());
  }

  function changePassword(event: InputChangeEvent): void {
    setPassword(event.currentTarget.value);
  }

  return (
    <Show when={state().locked && state().user}>
      {(user: Accessor<SessionUser>) => {
        return (
          <div data-testid="lock-screen" class={styles.overlay}>
            <div class={styles.grid} aria-hidden="true" />
            <div class={styles.panel}>
              {/* Hex emblem (prototype line 80) — the shared animated HUD
                  logo. While the reactor wait treatment is in flight,
                  ReactorRings wraps it with the spin-up arcs + pulse instead
                  of a bare HudLogo. */}
              <div class={styles.badge} aria-hidden="true">
                <Show
                  when={state().unlocking && state().waitVariant === "reactor"}
                  fallback={<HudLogo />}
                >
                  <ReactorRings>
                    <HudLogo />
                  </ReactorRings>
                </Show>
              </div>

              <div data-testid="lock-title" class={styles.title}>
                SESSION LOCKED
              </div>
              <div class={styles.subtitle}>
                REACTIVE TRADER OS · {user().id}
              </div>

              {/* Operator avatar — hex chip with initials (prototype line 83). */}
              <div class={styles.avatar}>
                <svg
                  viewBox="0 0 28 28"
                  class={styles.avatarHex}
                  aria-hidden="true"
                >
                  <polygon
                    points="14,1.5 25,7.75 25,20.25 14,26.5 3,20.25 3,7.75"
                    class={styles.avatarChip}
                    stroke="var(--accent-primary)"
                    stroke-width="1.3"
                  />
                </svg>
                <span class={styles.initials}>{user().initials}</span>
              </div>

              <div data-testid="lock-user-name" class={styles.name}>
                {user().name}
              </div>
              <div class={styles.role}>{user().role}</div>

              {/* Prototype order: the biometric dots sit between the role line and
                  the AUTHENTICATE button; the channel line stays below the button. */}
              <BiometricDots />

              <form class={styles.form} onSubmit={submitUnlock}>
                <div
                  class={
                    state().unlocking
                      ? `${waitStyles.fields} ${waitStyles.recede}`
                      : waitStyles.fields
                  }
                >
                  <label class={styles.field}>
                    <span class={styles.label}>Password</span>
                    <input
                      data-testid="lock-password"
                      class={styles.input}
                      type="password"
                      autocomplete="current-password"
                      value={password()}
                      onInput={changePassword}
                    />
                  </label>
                </div>

                <Show when={state().error !== null}>
                  <div data-testid="lock-error" class={styles.error}>
                    {state().error}
                  </div>
                </Show>

                <button
                  type="submit"
                  data-testid="lock-authenticate"
                  class={
                    state().unlocking
                      ? `${styles.authenticate} ${waitStyles.busy}`
                      : styles.authenticate
                  }
                  disabled={state().unlocking}
                >
                  {state().unlocking ? "AUTHENTICATING" : "AUTHENTICATE ▸"}
                </button>

                <Show
                  when={
                    state().unlocking && state().waitVariant === "handshake"
                  }
                >
                  <HandshakeConsole />
                </Show>
                <Show
                  when={state().unlocking && state().waitVariant === "reactor"}
                >
                  <ReactorWait />
                </Show>
              </form>

              <BiometricChannel />
            </div>
          </div>
        );
      }}
    </Show>
  );
}

type InputChangeEvent = Event & { currentTarget: HTMLInputElement };

// packages/client-react/src/ui/shell/lock/LockScreen.tsx
import type { ChangeEvent, FormEvent, ReactElement } from "react";
import { useState } from "react";

import { useViewModel } from "@rtc/react-bindings";

import { HandshakeConsole } from "../auth/wait/HandshakeConsole";
import { ReactorRings } from "../auth/wait/ReactorRings";
import { ReactorWait } from "../auth/wait/ReactorWait";
import { HudLogo } from "../logo/HudLogo";
import { BiometricChannel } from "./BiometricChannel";
import { BiometricDots } from "./BiometricDots";

import waitStyles from "../auth/wait/authWait.module.css";
import styles from "./LockScreen.module.css";

/**
 * Full-screen session-lock overlay (prototype Reactive Trader.dc.html:76-91).
 * Renders nothing unless the session is locked; while locked it shows the
 * operator identity and a password-gated AUTHENTICATE control that
 * re-authenticates (unlock) against the real credentials seam. Dumb
 * component: all state arrives through the `useAuth` hook seam; the typed
 * password lives in local component state only and is never logged.
 */
export function LockScreen(): ReactElement | null {
  const { useAuth } = useViewModel();
  const { state, unlock } = useAuth();

  const [password, setPassword] = useState("");

  if (!state.locked || !state.user) {
    return null;
  }

  const { user, unlocking } = state;
  const reactorWaiting = unlocking && state.waitVariant === "reactor";

  function submitUnlock(event: FormEvent<HTMLFormElement>): void {
    event.preventDefault();
    unlock(password);
  }

  function changePassword(event: ChangeEvent<HTMLInputElement>): void {
    setPassword(event.target.value);
  }

  return (
    <div data-testid="lock-screen" className={styles.overlay}>
      <div className={styles.grid} aria-hidden="true" />
      <div className={styles.panel}>
        {/* Hex emblem (prototype line 80) — the shared animated HUD logo.
            While the reactor wait treatment is in flight, ReactorRings wraps
            it with the spin-up arcs + pulse instead of a bare HudLogo. */}
        <div className={styles.badge} aria-hidden="true">
          {reactorWaiting ? (
            <ReactorRings>
              <HudLogo />
            </ReactorRings>
          ) : (
            <HudLogo />
          )}
        </div>

        <div data-testid="lock-title" className={styles.title}>
          SESSION LOCKED
        </div>
        <div className={styles.subtitle}>REACTIVE TRADER OS · {user.id}</div>

        {/* Operator avatar — hex chip with initials (prototype line 83). */}
        <div className={styles.avatar}>
          <svg
            viewBox="0 0 28 28"
            className={styles.avatarHex}
            aria-hidden="true"
          >
            <polygon
              points="14,1.5 25,7.75 25,20.25 14,26.5 3,20.25 3,7.75"
              className={styles.avatarChip}
              stroke="var(--accent-primary)"
              strokeWidth="1.3"
            />
          </svg>
          <span className={styles.initials}>{user.initials}</span>
        </div>

        <div data-testid="lock-user-name" className={styles.name}>
          {user.name}
        </div>
        <div className={styles.role}>{user.role}</div>

        {/* Prototype order: the biometric dots sit between the role line and
            the AUTHENTICATE button; the channel line stays below the button. */}
        <BiometricDots />

        <form className={styles.form} onSubmit={submitUnlock}>
          <div
            className={
              unlocking
                ? `${waitStyles.fields} ${waitStyles.recede}`
                : waitStyles.fields
            }
          >
            <label className={styles.field}>
              <span className={styles.label}>Password</span>
              <input
                data-testid="lock-password"
                className={styles.input}
                type="password"
                autoComplete="current-password"
                value={password}
                onChange={changePassword}
              />
            </label>
          </div>

          {state.error !== null ? (
            <div data-testid="lock-error" className={styles.error}>
              {state.error}
            </div>
          ) : null}

          <button
            type="submit"
            data-testid="lock-authenticate"
            className={
              unlocking
                ? `${styles.authenticate} ${waitStyles.busy}`
                : styles.authenticate
            }
            disabled={unlocking}
          >
            {unlocking ? "AUTHENTICATING" : "AUTHENTICATE ▸"}
          </button>

          {unlocking && state.waitVariant === "handshake" ? (
            <HandshakeConsole />
          ) : null}
          {unlocking && state.waitVariant === "reactor" ? (
            <ReactorWait />
          ) : null}
        </form>

        <BiometricChannel />
      </div>
    </div>
  );
}
