// packages/client-react/src/ui/shell/status/StatusBar.tsx
import type { ReactElement } from "react";

import { useViewModel } from "@rtc/react-bindings";

import { ConnectionStatusBar } from "../connection/ConnectionStatusBar";
import { CosmeticMetrics } from "./CosmeticMetrics";
import { JarvisStatusChip } from "./JarvisStatusChip";

import styles from "./StatusBar.module.css";

/**
 * HUD bottom status bar — ported from the prototype footer
 * (Reactive Trader.dc.html:720-730). The connection segment reuses the real
 * `ConnectionStatusBar` (carries the `connection-status` e2e testid, driven by
 * `useConnectionStatus`); the operator segment is wired to the auth seam
 * (`useAuth`); `JarvisStatusChip` reports the active brain (hidden while
 * Jarvis is unavailable); the latency/FPS/MEM/POS/P&L + build + clock
 * readouts are decorative (see CosmeticMetrics).
 */
export function StatusBar(): ReactElement {
  const { useAuth } = useViewModel();
  const { state } = useAuth();

  return (
    <footer className={styles.statusBar}>
      <ConnectionStatusBar />
      <span className={styles.metricSep}>│</span>
      <span className={styles.operator} data-testid="status-operator">
        {state.user?.id ?? ""}
      </span>
      <span className={styles.metricSep}>│</span>
      <JarvisStatusChip />
      <CosmeticMetrics />
    </footer>
  );
}

// packages/client-solid/src/ui/shell/status/StatusBar.tsx
import type { JSX } from "solid-js";

import { useViewModel } from "@rtc/solid-bindings";

import { ConnectionStatusBar } from "../connection/ConnectionStatusBar";
import { CosmeticMetrics } from "./CosmeticMetrics";
import { JarvisStatusChip } from "./JarvisStatusChip";

import styles from "./StatusBar.module.css";

/**
 * HUD bottom status bar — ported from the prototype footer
 * (Reactive Trader.dc.html:720-730). The connection segment reuses the real
 * `ConnectionStatusBar` (carries the `connection-status` e2e testid, driven by
 * `useConnectionStatus`); the operator segment is wired to the auth seam
 * (`useAuth`); `JarvisStatusChip` reports the active brain (hidden while
 * Jarvis is unavailable); the latency/FPS/MEM/POS/P&L + build + clock
 * readouts are decorative (see CosmeticMetrics).
 */
export function StatusBar(): JSX.Element {
  const { useAuth } = useViewModel();
  const { state } = useAuth();

  return (
    <footer class={styles.statusBar}>
      <ConnectionStatusBar />
      <span class={styles.metricSep}>│</span>
      <span class={styles.operator} data-testid="status-operator">
        {state().user?.id ?? ""}
      </span>
      <span class={styles.metricSep}>│</span>
      <JarvisStatusChip />
      <CosmeticMetrics />
    </footer>
  );
}
