// packages/client-solid/src/ui/fx/analytics/PnlValue.tsx
import type { JSX } from "solid-js";
import { createMemo } from "solid-js";

import { formatPnlHeadline } from "@rtc/domain";

import styles from "./PnlValue.module.css";

export function PnlValue(props: PnlValueProps): JSX.Element {
  const sign = createMemo((): "pos" | "neg" => {
    return props.value >= 0 ? "pos" : "neg";
  });

  return (
    <div data-sign={sign()} class={styles.value}>
      <span class={styles.amount} data-testid="lastPosition">
        {formatPnlHeadline(props.value)}
      </span>
    </div>
  );
}

interface PnlValueProps {
  value: number;
}

// packages/client-react/src/ui/fx/analytics/PnlValue.tsx
import type { ReactElement } from "react";

import { formatPnlHeadline } from "@rtc/domain";

import styles from "./PnlValue.module.css";

export function PnlValue({ value }: PnlValueProps): ReactElement {
  const sign = value >= 0 ? "pos" : "neg";

  return (
    <div data-sign={sign} className={styles.value}>
      <span className={styles.amount} data-testid="lastPosition">
        {formatPnlHeadline(value)}
      </span>
    </div>
  );
}

interface PnlValueProps {
  value: number;
}
