// packages/client/src/stale/stale-indicator.tsx
import type { CSSProperties, ReactNode } from "react";

interface StaleIndicatorProps {
  stale: boolean;
  children: ReactNode;
  style?: CSSProperties;
}

/**
 * Wraps children with a greyed-out overlay when data is stale.
 */
export function StaleIndicator({ stale, children, style }: StaleIndicatorProps) {
  return (
    <div
      data-stale={stale || undefined}
      style={{
        position: "relative",
        ...style,
      }}
    >
      {children}
      {stale && (
        <div
          style={{
            position: "absolute",
            inset: 0,
            backgroundColor: "rgba(0, 0, 0, 0.4)",
            borderRadius: "inherit",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            zIndex: 10,
          }}
        >
          <span
            style={{
              fontSize: 11,
              color: "rgba(255, 255, 255, 0.8)",
              fontWeight: 500,
            }}
          >
            Reconnecting...
          </span>
        </div>
      )}
    </div>
  );
}

// packages/client-solid/src/ui/shell/stale/StaleIndicator.tsx
import type { JSX } from "solid-js";
import { Show } from "solid-js";

import styles from "./StaleIndicator.module.css";

/**
 * Wraps children with a greyed-out overlay when data is stale.
 */
export function StaleIndicator(props: StaleIndicatorProps): JSX.Element {
  return (
    <div
      data-stale={props.stale || undefined}
      class={styles.wrapper}
      style={props.style}
    >
      {props.children}
      <Show when={props.stale}>
        <div class={styles.overlay}>
          <span data-testid="stale-message" class={styles.message}>
            Reconnecting...
          </span>
        </div>
      </Show>
    </div>
  );
}

interface StaleIndicatorProps {
  stale: boolean;
  children: JSX.Element;
  style?: JSX.CSSProperties;
}
