// packages/client-solid/src/ui/shell/auth/LoginScreen.tsx
import type { JSX } from "solid-js";
import { createSignal, Show } from "solid-js";

import { useViewModel } from "@rtc/solid-bindings";

import { HudLogo } from "../logo/HudLogo";

import styles from "./LoginScreen.module.css";

/**
 * Full-screen sign-in form (prototype-styled to match LockScreen). Renders
 * unconditionally while mounted — AuthGate mounts it only for the
 * unauthenticated branch of the auth lifecycle. Dumb component: all state
 * arrives through the `useAuth` seam; the typed credentials live in local
 * signals only and are never logged.
 */
export function LoginScreen(): JSX.Element {
  const { useAuth } = useViewModel();
  const { state, login } = useAuth();

  const [username, setUsername] = createSignal("");
  const [password, setPassword] = createSignal("");

  return (
    <div data-testid="login-screen" class={styles.overlay}>
      <div class={styles.grid} aria-hidden="true" />
      <div class={styles.panel}>
        <div class={styles.badge} aria-hidden="true">
          <HudLogo />
        </div>

        <div data-testid="login-title" class={styles.title}>
          REACTIVE TRADER OS · SIGN IN
        </div>

        <form
          class={styles.form}
          onSubmit={(event: SubmitEvent) => {
            event.preventDefault();
            login(username(), password());
          }}
        >
          <label class={styles.field}>
            <span class={styles.label}>Username</span>
            <input
              data-testid="login-username"
              class={styles.input}
              type="text"
              autocomplete="username"
              value={username()}
              onInput={(event: InputChangeEvent) => {
                setUsername(event.currentTarget.value);
              }}
            />
          </label>

          <label class={styles.field}>
            <span class={styles.label}>Password</span>
            <input
              data-testid="login-password"
              class={styles.input}
              type="password"
              autocomplete="current-password"
              value={password()}
              onInput={(event: InputChangeEvent) => {
                setPassword(event.currentTarget.value);
              }}
            />
          </label>

          <Show when={state().error !== null}>
            <div data-testid="login-error" class={styles.error}>
              {state().error}
            </div>
          </Show>

          <button
            type="submit"
            data-testid="login-submit"
            class={styles.submit}
            disabled={state().status === "authenticating"}
          >
            AUTHENTICATE ▸
          </button>
        </form>
      </div>
    </div>
  );
}

type InputChangeEvent = Event & { currentTarget: HTMLInputElement };

// packages/client-react-native/src/ui/shell/auth/LoginScreen.tsx
import type { JSX } from "react";
import { useState } from "react";
import {
  KeyboardAvoidingView,
  Platform,
  Pressable,
  ScrollView,
  StyleSheet,
  Switch,
  Text,
  TextInput,
  type TextStyle,
  View,
  type ViewStyle,
} from "react-native";
import Svg, { Circle, Polygon } from "react-native-svg";

import { useViewModel } from "@rtc/react-bindings";

import type { RnTheme } from "#/ui/theme/tokens";
import { useTheme } from "#/ui/theme/useTheme";
import { useThemedStyles } from "#/ui/theme/useThemedStyles";

/** Full-screen sign-in form — the RN analogue of the web client's
 * `LoginScreen`, styled to match `LockScreen`'s hex-emblem overlay. Renders
 * unconditionally while mounted; `AuthGate` is expected to mount it only for
 * the non-"authenticated" branch of the auth lifecycle. Dumb component: all
 * state arrives through the `useAuth` hook seam, the typed credentials live
 * in local component state only, and the password is never logged.
 * `simulator`/`onToggleSimulator` surface the same Sim/Live toggle `Chrome`
 * renders post-auth, so it's reachable before signing in — the only such
 * toggle when the app boots against a sleeping or credential-less live
 * server. Wrapped in `KeyboardAvoidingView` + a `ScrollView` with
 * `keyboardShouldPersistTaps="handled"` so the soft keyboard never strands
 * the submit control on a real device. */
export function LoginScreen({
  simulator,
  onToggleSimulator,
}: LoginScreenProps): JSX.Element {
  const { useAuth } = useViewModel();
  const { state, login } = useAuth();
  const theme = useTheme();
  const styles = useThemedStyles(makeStyles);

  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");

  const authenticating = state.status === "authenticating";

  return (
    <KeyboardAvoidingView
      testID="login-screen"
      style={styles.overlay}
      behavior={Platform.OS === "ios" ? "padding" : "height"}
    >
      <ScrollView
        style={styles.scroll}
        contentContainerStyle={styles.scrollContent}
        keyboardShouldPersistTaps="handled"
      >
        <Svg width={72} height={72} viewBox="0 0 48 48">
          <Polygon
            points="24,3 40.6,13.5 40.6,34.5 24,45 7.4,34.5 7.4,13.5"
            fill="none"
            stroke={theme.accentPrimary}
            strokeWidth={1.3}
          />
          <Polygon
            points="24,8 36.3,15.75 36.3,31.25 24,39 11.7,31.25 11.7,15.75"
            fill="none"
            stroke={theme.accent2}
            strokeWidth={1}
            opacity={0.6}
          />
          <Circle cx={24} cy={24} r={3.4} fill={theme.accentPrimary} />
        </Svg>

        <Text testID="login-title" style={styles.title}>
          REACTIVE TRADER OS · SIGN IN
        </Text>

        <View style={styles.field}>
          <Text style={styles.label}>Username</Text>
          <TextInput
            testID="login-username"
            value={username}
            onChangeText={setUsername}
            autoCapitalize="none"
            autoCorrect={false}
            placeholder="Enter username..."
            placeholderTextColor={styles.placeholder.color}
            style={styles.input}
          />
        </View>

        <View style={styles.field}>
          <Text style={styles.label}>Password</Text>
          <TextInput
            testID="login-password"
            value={password}
            onChangeText={setPassword}
            secureTextEntry
            autoCapitalize="none"
            autoCorrect={false}
            placeholder="Enter password..."
            placeholderTextColor={styles.placeholder.color}
            style={styles.input}
          />
        </View>

        {state.error !== null ? (
          <Text testID="login-error" style={styles.error}>
            {state.error}
          </Text>
        ) : null}

        <Pressable
          testID="login-submit"
          disabled={authenticating}
          onPress={() => {
            login(username, password);
          }}
        >
          <Text
            style={[
              styles.submit,
              authenticating ? styles.submitDisabled : null,
            ]}
          >
            AUTHENTICATE ▸
          </Text>
        </Pressable>

        <View style={styles.simRow}>
          <Text style={styles.simLabel}>Simulator mode</Text>
          <Switch
            testID="login-sim-toggle"
            value={simulator}
            onValueChange={onToggleSimulator}
          />
        </View>
      </ScrollView>
    </KeyboardAvoidingView>
  );
}

interface LoginScreenProps {
  simulator: boolean;
  onToggleSimulator: (value: boolean) => void;
}

interface LoginScreenStyles {
  overlay: ViewStyle;
  scroll: ViewStyle;
  scrollContent: ViewStyle;
  title: TextStyle;
  field: ViewStyle;
  label: TextStyle;
  input: TextStyle;
  placeholder: TextStyle;
  error: TextStyle;
  submit: TextStyle;
  submitDisabled: TextStyle;
  simRow: ViewStyle;
  simLabel: TextStyle;
}

function makeStyles(t: RnTheme): LoginScreenStyles {
  return StyleSheet.create({
    overlay: {
      ...StyleSheet.absoluteFill,
      backgroundColor: t.bgPrimary,
    },
    scroll: { flex: 1 },
    scrollContent: {
      flexGrow: 1,
      alignItems: "center",
      justifyContent: "center",
      gap: 10,
      padding: 24,
    },
    title: {
      color: t.textPrimary,
      fontFamily: t.fontDisplay,
      fontSize: 18,
      letterSpacing: 3,
      marginBottom: 8,
      textAlign: "center",
    },
    field: { width: "100%", maxWidth: 320, gap: 4 },
    label: {
      color: t.textSecondary,
      fontFamily: t.fontDisplay,
      fontSize: 12,
      letterSpacing: 1,
    },
    input: {
      borderWidth: 1,
      borderColor: t.borderSubtle,
      borderRadius: 6,
      padding: 10,
      color: t.textPrimary,
      fontFamily: t.fontMono,
    },
    placeholder: { color: t.textMuted },
    error: {
      color: t.accentNegative,
      fontFamily: t.fontMono,
      fontSize: 12,
      marginTop: 4,
    },
    submit: {
      color: t.accentPrimary,
      fontFamily: t.fontDisplay,
      fontSize: 14,
      letterSpacing: 1,
      marginTop: 12,
    },
    submitDisabled: { color: t.textMuted },
    simRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      marginTop: 20,
    },
    simLabel: { color: t.textMuted, fontFamily: t.fontDisplay, fontSize: 12 },
  });
}
