// packages/client-solid/src/ui/fx/liveRates/tile/RfqCountdown.tsx
import type { JSX } from "solid-js";
import { createMemo } from "solid-js";

import styles from "./RfqCountdown.module.css";

export function RfqCountdown(props: RfqCountdownProps): JSX.Element {
  const fraction = createMemo((): number => {
    return props.totalMs > 0 ? props.remainingMs / props.totalMs : 0;
  });
  const seconds = createMemo((): number => {
    return Math.ceil(props.remainingMs / 1000);
  });
  // Captured ONCE at component setup (Solid components run their body once
  // per mount, the direct analogue of React's `useState(() => ...)`
  // initializer): the fill is a single mount-time CSS animation over the RFQ
  // window, fast-forwarded via a negative animation-delay — NOT re-driven
  // per tick (per-tick geometry writes kept a main-thread animation alive
  // every frame; see RfqCountdown.module.css .fill).
  const drainTiming: JSX.CSSProperties = {
    "--rfq-duration": `${props.totalMs}ms`,
    "--rfq-delay": `${Math.min(0, props.remainingMs - props.totalMs)}ms`,
  };

  return (
    <div class={styles.wrapper}>
      <div class={styles.track}>
        <div
          data-testid="rfq-countdown-fill"
          data-warn={fraction() <= 0.3 ? "true" : "false"}
          class={styles.fill}
          style={drainTiming}
        />
      </div>
      <span class={styles.caption}>{seconds()}s remaining</span>
    </div>
  );
}

interface RfqCountdownProps {
  remainingMs: number;
  totalMs: number;
}

// packages/client-react/src/ui/fx/liveRates/tile/RfqCountdown.tsx
import type { CSSProperties, ReactElement } from "react";
import { useState } from "react";

import styles from "./RfqCountdown.module.css";

export function RfqCountdown({
  remainingMs,
  totalMs,
}: RfqCountdownProps): ReactElement {
  const fraction = totalMs > 0 ? remainingMs / totalMs : 0;
  const seconds = Math.ceil(remainingMs / 1000);
  // Captured ONCE at mount (useState initializer): the fill is a single
  // mount-time CSS animation over the RFQ window, fast-forwarded via a
  // negative animation-delay — NOT re-driven per tick (per-tick geometry
  // writes kept a main-thread animation alive every frame; see
  // RfqCountdown.module.css .fill).
  const [drainTiming] = useState<CSSProperties>(() => {
    return {
      "--rfq-duration": `${totalMs}ms`,
      "--rfq-delay": `${Math.min(0, remainingMs - totalMs)}ms`,
    } as CSSProperties;
  });

  return (
    <div className={styles.wrapper}>
      <div className={styles.track}>
        <div
          data-testid="rfq-countdown-fill"
          data-warn={fraction <= 0.3 ? "true" : "false"}
          className={styles.fill}
          style={drainTiming}
        />
      </div>
      <span className={styles.caption}>{seconds}s remaining</span>
    </div>
  );
}

interface RfqCountdownProps {
  remainingMs: number;
  totalMs: number;
}
