// packages/client-solid/src/ui/fx/liveRates/tile/TileNotional.tsx
import type { Accessor, JSX } from "solid-js";
import { createMemo, Show } from "solid-js";

import type { NotionalIntents, NotionalView } from "@rtc/client-core";

import styles from "./TileNotional.module.css";

export function TileNotional(props: TileNotionalProps): JSX.Element {
  let inputRef!: HTMLInputElement;

  function handleChange(e: InputChangeEvent): void {
    props.notional.change(e.currentTarget.value);
  }

  function handleKeyDown(e: InputKeyDownEvent): void {
    if (e.key === "Enter") {
      inputRef.blur();
    }
  }

  function handleFocus(): void {
    inputRef.select();
  }

  const hasError = createMemo((): boolean => {
    return !!props.notional.state().error;
  });

  return (
    <div class={styles.wrapper}>
      <span class={styles.currencyLabel}>{props.baseCurrency}</span>
      <div class={styles.inputArea}>
        <input
          ref={inputRef}
          value={props.notional.state().displayValue}
          onChange={handleChange}
          onKeyDown={handleKeyDown}
          onFocus={handleFocus}
          disabled={props.disabled}
          data-error={hasError() ? "true" : "false"}
          class={styles.input}
        />
        <Show when={!props.notional.state().isDefault}>
          <button
            type="button"
            onClick={() => {
              props.notional.reset();
            }}
            title="Reset to default"
            class={styles.resetButton}
          >
            {"↺"}
          </button>
        </Show>
      </div>
      <Show when={hasError()}>
        <span class={styles.maxTag}>MAX</span>
      </Show>
      <Show when={hasError()}>
        <span data-testid="notional-error" class={styles.errorMessage}>
          {props.notional.state().error}
        </span>
      </Show>
    </div>
  );
}

interface TileNotionalProps {
  notional: NotionalMachine;
  baseCurrency: string;
  disabled?: boolean;
}

type NotionalMachine = { state: Accessor<NotionalView> } & NotionalIntents;
type InputChangeEvent = Event & { currentTarget: HTMLInputElement };
type InputKeyDownEvent = KeyboardEvent & { currentTarget: HTMLInputElement };

// packages/client-react/src/ui/fx/liveRates/tile/TileNotional.tsx
import {
  type ChangeEvent,
  type KeyboardEvent,
  useCallback,
  useRef,
} from "react";
import type {
  NotionalIntents,
  NotionalView,
} from "../../../../app/presenters/NotionalMachine";
import styles from "./TileNotional.module.css";

interface TileNotionalProps {
  notional: { state: NotionalView } & NotionalIntents;
  baseCurrency: string;
  disabled?: boolean;
}

export function TileNotional({
  notional,
  baseCurrency,
  disabled,
}: TileNotionalProps) {
  const inputRef = useRef<HTMLInputElement>(null);

  const handleChange = useCallback(
    (e: ChangeEvent<HTMLInputElement>) => {
      notional.change(e.target.value);
    },
    [notional],
  );

  const handleKeyDown = useCallback((e: KeyboardEvent<HTMLInputElement>) => {
    if (e.key === "Enter") {
      inputRef.current?.blur();
    }
  }, []);

  const handleFocus = useCallback(() => {
    inputRef.current?.select();
  }, []);

  const hasError = !!notional.state.error;

  return (
    <div className={styles.wrapper}>
      <span className={styles.currencyLabel}>{baseCurrency}</span>
      <input
        ref={inputRef}
        value={notional.state.displayValue}
        onChange={handleChange}
        onKeyDown={handleKeyDown}
        onFocus={handleFocus}
        disabled={disabled}
        data-error={hasError ? "true" : "false"}
        className={styles.input}
      />
      {!notional.state.isDefault && (
        <button
          onClick={notional.reset}
          title="Reset to default"
          className={styles.resetButton}
        >
          {"↺"}
        </button>
      )}
      {hasError && (
        <span data-testid="notional-error" className={styles.errorMessage}>
          {notional.state.error}
        </span>
      )}
    </div>
  );
}
