// packages/client-solid/src/ui/credit/newRfq/NewRfqHead.tsx
import type { JSX } from "solid-js";

import styles from "#/ui/shell/layout/engine/PanelHeadTabs.module.css";

/** The credit-new-rfq panel's head slot: a single, always-active "✚ New RFQ"
 * tab — this panel has only one view, so nothing ever toggles it. Reuses the
 * same accent-underline tab chrome as the FX panel heads
 * (PanelHeadTabs.module.css from #105) so the credit dock's heads read as one
 * chrome family with FX. Renders inside the panel header via
 * InhouseLayoutEngine's headRegistry; the collapse/maximize controls stay
 * next to it, owned by the engine, not this component. */
export function NewRfqHead(): JSX.Element {
  return (
    <div class={styles.headTabs}>
      <span
        data-testid="new-rfq-head-title"
        data-active="true"
        class={styles.headTab}
      >
        ✚ New RFQ
      </span>
    </div>
  );
}

// packages/client-react/src/ui/credit/newRfq/NewRfqHead.tsx
import type { ReactElement } from "react";

import styles from "#/ui/shell/layout/engine/PanelHeadTabs.module.css";

/** The credit-new-rfq panel's head slot: a single, always-active "✚ New RFQ"
 * tab — this panel has only one view, so nothing ever toggles it. Reuses the
 * same accent-underline tab chrome as the FX panel heads
 * (PanelHeadTabs.module.css from #105) so the credit dock's heads read as one
 * chrome family with FX. Renders inside the panel header via
 * InhouseLayoutEngine's headRegistry; the collapse/maximize controls stay
 * next to it, owned by the engine, not this component. */
export function NewRfqHead(): ReactElement {
  return (
    <div className={styles.headTabs}>
      <span
        data-testid="new-rfq-head-title"
        data-active="true"
        className={styles.headTab}
      >
        ✚ New RFQ
      </span>
    </div>
  );
}
