// packages/client-solid/src/ui/fx/blotter/columnFilter/NumberFilter.tsx
import type { JSX } from "solid-js";
import { createSignal, For, Show } from "solid-js";

import type { ColumnFilter, Comparator } from "@rtc/client-core";

import styles from "./NumberFilter.module.css";

export function NumberFilter<TRow>(
  props: NumberFilterProps<TRow>,
): JSX.Element {
  const [comparator, setComparator] = createSignal<Comparator>(
    props.currentFilter?.type === "number"
      ? props.currentFilter.comparator
      : "eq",
  );
  const [value, setValue] = createSignal(
    props.currentFilter?.type === "number"
      ? String(props.currentFilter.value)
      : "",
  );
  const [valueTo, setValueTo] = createSignal(
    props.currentFilter?.type === "number" &&
      props.currentFilter.valueTo != null
      ? String(props.currentFilter.valueTo)
      : "",
  );

  function handleApply(): void {
    const num = Number.parseFloat(value());

    if (Number.isNaN(num)) {
      props.onApply(null);
      return;
    }

    const numTo =
      comparator() === "inRange" ? Number.parseFloat(valueTo()) : undefined;
    props.onApply({
      type: "number",
      column: props.column,
      comparator: comparator(),
      value: num,
      valueTo: numTo !== undefined && !Number.isNaN(numTo) ? numTo : undefined,
    });
  }

  return (
    <div class={styles.container}>
      <select
        data-testid="number-filter-comparator"
        value={comparator()}
        onChange={(e: SelectChangeEvent): void => {
          setComparator(e.currentTarget.value as Comparator);
        }}
        class={styles.select}
      >
        <For each={comparators}>
          {(c: ComparatorOption) => {
            return <option value={c.value}>{c.label}</option>;
          }}
        </For>
      </select>
      <input
        type="number"
        data-testid="number-filter-value"
        value={value()}
        // React's onChange fires per keystroke (native `input` event);
        // Solid's onChange maps to native `change` only (fires on blur) —
        // both wired here so real typing (`input`) and a programmatic
        // `change` dispatch both narrow live (wiring both is idempotent,
        // see TileNotional's identical comment).
        onInput={(e: InputChangeEvent): void => {
          setValue(e.currentTarget.value);
        }}
        onChange={(e: InputChangeEvent): void => {
          setValue(e.currentTarget.value);
        }}
        placeholder="Value"
        class={styles.input}
      />
      <Show when={comparator() === "inRange"}>
        <input
          type="number"
          data-testid="number-filter-value-to"
          value={valueTo()}
          onInput={(e: InputChangeEvent): void => {
            setValueTo(e.currentTarget.value);
          }}
          onChange={(e: InputChangeEvent): void => {
            setValueTo(e.currentTarget.value);
          }}
          placeholder="To"
          class={styles.input}
        />
      </Show>
      <div class={styles.buttons}>
        <button
          type="button"
          data-testid="number-filter-apply"
          onClick={handleApply}
          class={styles.applyBtn}
        >
          Apply
        </button>
        <button
          type="button"
          onClick={() => {
            props.onApply(null);
          }}
          class={styles.resetBtn}
        >
          Reset
        </button>
      </div>
    </div>
  );
}

interface NumberFilterProps<TRow> {
  column: keyof TRow;
  currentFilter: ColumnFilter<TRow> | undefined;
  onApply: (filter: ColumnFilter<TRow> | null) => void;
}

type SelectChangeEvent = Event & { currentTarget: HTMLSelectElement };
type InputChangeEvent = Event & { currentTarget: HTMLInputElement };

interface ComparatorOption {
  value: Comparator;
  label: string;
}

const comparators: ComparatorOption[] = [
  { value: "eq", label: "Equals" },
  { value: "neq", label: "Not equal" },
  { value: "lt", label: "Less than" },
  { value: "lte", label: "Less than or equals" },
  { value: "gt", label: "Greater than" },
  { value: "gte", label: "Greater than or equals" },
  { value: "inRange", label: "In range" },
];

// packages/client/src/blotter/column-filter/number-filter.tsx
import { useCallback, useState } from "react";
import type { Trade } from "@rtc/domain";
import type { ColumnFilter, Comparator } from "./filter-state";

interface NumberFilterProps {
  column: keyof Trade;
  currentFilter: ColumnFilter | undefined;
  onApply: (filter: ColumnFilter | null) => void;
}

const comparators: { value: Comparator; label: string }[] = [
  { value: "eq", label: "Equals" },
  { value: "neq", label: "Not equal" },
  { value: "lt", label: "Less than" },
  { value: "lte", label: "Less than or equals" },
  { value: "gt", label: "Greater than" },
  { value: "gte", label: "Greater than or equals" },
  { value: "inRange", label: "In range" },
];

export function NumberFilter({ column, currentFilter, onApply }: NumberFilterProps) {
  const [comparator, setComparator] = useState<Comparator>(
    currentFilter?.type === "number" ? currentFilter.comparator : "eq",
  );
  const [value, setValue] = useState(
    currentFilter?.type === "number" ? String(currentFilter.value) : "",
  );
  const [valueTo, setValueTo] = useState(
    currentFilter?.type === "number" && currentFilter.valueTo != null
      ? String(currentFilter.valueTo)
      : "",
  );

  const handleApply = useCallback(() => {
    const num = parseFloat(value);
    if (isNaN(num)) {
      onApply(null);
      return;
    }
    const numTo = comparator === "inRange" ? parseFloat(valueTo) : undefined;
    onApply({
      type: "number",
      column,
      comparator,
      value: num,
      valueTo: numTo !== undefined && !isNaN(numTo) ? numTo : undefined,
    });
  }, [column, comparator, value, valueTo, onApply]);

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 4, padding: 8 }}>
      <select
        value={comparator}
        onChange={(e) => setComparator(e.target.value as Comparator)}
        style={{ fontSize: 11, padding: 2, color: "var(--text-primary)", backgroundColor: "var(--bg-secondary)", border: "1px solid var(--border-primary)" }}
      >
        {comparators.map((c) => (
          <option key={c.value} value={c.value}>{c.label}</option>
        ))}
      </select>
      <input
        type="number"
        value={value}
        onChange={(e) => setValue(e.target.value)}
        placeholder="Value"
        style={{ fontSize: 11, padding: 2, color: "var(--text-primary)", backgroundColor: "var(--bg-secondary)", border: "1px solid var(--border-primary)" }}
      />
      {comparator === "inRange" && (
        <input
          type="number"
          value={valueTo}
          onChange={(e) => setValueTo(e.target.value)}
          placeholder="To"
          style={{ fontSize: 11, padding: 2, color: "var(--text-primary)", backgroundColor: "var(--bg-secondary)", border: "1px solid var(--border-primary)" }}
        />
      )}
      <div style={{ display: "flex", gap: 4 }}>
        <button
          onClick={handleApply}
          style={{ flex: 1, padding: "4px 8px", fontSize: 11, border: "1px solid var(--border-primary)", borderRadius: 3, backgroundColor: "var(--accent-primary)", color: "#fff", cursor: "pointer" }}
        >
          Apply
        </button>
        <button
          onClick={() => onApply(null)}
          style={{ flex: 1, padding: "4px 8px", fontSize: 11, border: "1px solid var(--border-primary)", borderRadius: 3, backgroundColor: "transparent", color: "var(--text-secondary)", cursor: "pointer" }}
        >
          Reset
        </button>
      </div>
    </div>
  );
}
