// packages/client-react-native/src/ui/analytics/PnlValue.tsx
import type { JSX } from "react";
import { StyleSheet, Text } from "react-native";

import { formatPnlValue } from "@rtc/domain";

export function PnlValue({ value }: PnlValueProps): JSX.Element {
  const color = value >= 0 ? styles.pos : styles.neg;
  return (
    <Text testID="pnl-value" style={[styles.value, color]}>
      USD {formatPnlValue(value)}
    </Text>
  );
}

interface PnlValueProps {
  value: number;
}

const styles = StyleSheet.create({
  value: { fontSize: 20, fontWeight: "600" },
  pos: { color: "#3fb68b" },
  neg: { color: "#e05252" },
});

// packages/client-solid/src/ui/fx/analytics/PnlValue.tsx
import type { JSX } from "solid-js";
import { createMemo } from "solid-js";

import { formatPnlHeadline } from "@rtc/domain";

import styles from "./PnlValue.module.css";

export function PnlValue(props: PnlValueProps): JSX.Element {
  const sign = createMemo((): "pos" | "neg" => {
    return props.value >= 0 ? "pos" : "neg";
  });

  return (
    <div data-sign={sign()} class={styles.value}>
      <span class={styles.amount} data-testid="lastPosition">
        {formatPnlHeadline(props.value)}
      </span>
    </div>
  );
}

interface PnlValueProps {
  value: number;
}
