// packages/client/src/ui/fx/blotter/columnFilter/DateFilter.tsx
import { useCallback, useState } from "react";
import type { Trade } from "@rtc/domain";
import type { ColumnFilter, Comparator } from "./filterState";

interface DateFilterProps {
  column: keyof Trade;
  currentFilter: ColumnFilter | undefined;
  onApply: (filter: ColumnFilter | null) => void;
}

const comparators: { value: Comparator; label: string }[] = [
  { value: "eq", label: "Equals" },
  { value: "neq", label: "Not equal" },
  { value: "lt", label: "Less than" },
  { value: "lte", label: "Less than or equals" },
  { value: "gt", label: "Greater than" },
  { value: "gte", label: "Greater than or equals" },
  { value: "inRange", label: "In range" },
];

export function DateFilter({ column, currentFilter, onApply }: DateFilterProps) {
  const [comparator, setComparator] = useState<Comparator>(
    currentFilter?.type === "date" ? currentFilter.comparator : "eq",
  );
  const [value, setValue] = useState(
    currentFilter?.type === "date" ? currentFilter.value : "",
  );
  const [valueTo, setValueTo] = useState(
    currentFilter?.type === "date" && currentFilter.valueTo ? currentFilter.valueTo : "",
  );

  const handleApply = useCallback(() => {
    if (!value) {
      onApply(null);
      return;
    }
    onApply({
      type: "date",
      column,
      comparator,
      value,
      valueTo: comparator === "inRange" ? valueTo : undefined,
    });
  }, [column, comparator, value, valueTo, onApply]);

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 4, padding: 8 }}>
      <select
        data-testid="date-filter-comparator"
        value={comparator}
        onChange={(e) => setComparator(e.target.value as Comparator)}
        style={{ fontSize: 11, padding: 2, color: "var(--text-primary)", backgroundColor: "var(--bg-secondary)", border: "1px solid var(--border-primary)" }}
      >
        {comparators.map((c) => (
          <option key={c.value} value={c.value}>{c.label}</option>
        ))}
      </select>
      <input
        type="date"
        data-testid="date-filter-value"
        value={value}
        onChange={(e) => setValue(e.target.value)}
        style={{ fontSize: 11, padding: 2, color: "var(--text-primary)", backgroundColor: "var(--bg-secondary)", border: "1px solid var(--border-primary)" }}
      />
      {comparator === "inRange" && (
        <input
          type="date"
          data-testid="date-filter-value-to"
          value={valueTo}
          onChange={(e) => setValueTo(e.target.value)}
          style={{ fontSize: 11, padding: 2, color: "var(--text-primary)", backgroundColor: "var(--bg-secondary)", border: "1px solid var(--border-primary)" }}
        />
      )}
      <div style={{ display: "flex", gap: 4 }}>
        <button
          data-testid="date-filter-apply"
          onClick={handleApply}
          style={{ flex: 1, padding: "4px 8px", fontSize: 11, border: "1px solid var(--border-primary)", borderRadius: 3, backgroundColor: "var(--accent-primary)", color: "#fff", cursor: "pointer" }}
        >
          Apply
        </button>
        <button
          onClick={() => onApply(null)}
          style={{ flex: 1, padding: "4px 8px", fontSize: 11, border: "1px solid var(--border-primary)", borderRadius: 3, backgroundColor: "transparent", color: "var(--text-secondary)", cursor: "pointer" }}
        >
          Reset
        </button>
      </div>
    </div>
  );
}

// packages/client-solid/src/ui/fx/blotter/columnFilter/DateFilter.tsx
import type { JSX } from "solid-js";
import { createSignal, For, Show } from "solid-js";

import type { ColumnFilter, Comparator } from "@rtc/client-core";

import styles from "./DateFilter.module.css";

export function DateFilter<TRow>(props: DateFilterProps<TRow>): JSX.Element {
  const [comparator, setComparator] = createSignal<Comparator>(
    // eslint-disable-next-line solid/reactivity -- setup-scope read is intentional: this component remounts when the value changes
    props.currentFilter?.type === "date"
      ? // eslint-disable-next-line solid/reactivity -- setup-scope read is intentional: this component remounts when the value changes
        props.currentFilter.comparator
      : "eq",
  );
  const [value, setValue] = createSignal(
    // eslint-disable-next-line solid/reactivity -- setup-scope read is intentional: this component remounts when the value changes
    props.currentFilter?.type === "date" ? props.currentFilter.value : "",
  );
  const [valueTo, setValueTo] = createSignal(
    // eslint-disable-next-line solid/reactivity -- setup-scope read is intentional: this component remounts when the value changes
    props.currentFilter?.type === "date" && props.currentFilter.valueTo
      ? // eslint-disable-next-line solid/reactivity -- setup-scope read is intentional: this component remounts when the value changes
        props.currentFilter.valueTo
      : "",
  );

  function handleApply(): void {
    if (!value()) {
      props.onApply(null);
      return;
    }

    props.onApply({
      type: "date",
      column: props.column,
      comparator: comparator(),
      value: value(),
      valueTo: comparator() === "inRange" ? valueTo() : undefined,
    });
  }

  return (
    <div class={styles.container}>
      <select
        data-testid="date-filter-comparator"
        value={comparator()}
        onChange={(e: SelectChangeEvent): void => {
          setComparator(e.currentTarget.value as Comparator);
        }}
        class={styles.select}
      >
        <For each={comparators}>
          {(c: ComparatorOption) => {
            return <option value={c.value}>{c.label}</option>;
          }}
        </For>
      </select>
      <input
        type="date"
        data-testid="date-filter-value"
        value={value()}
        // Native date inputs report edits via `change` (browsers don't fire
        // `input` reliably per keystroke for them, and the contract spec's
        // DateFilterPage drives them with `fireEvent.change` for exactly
        // that reason) — `onInput` wired too for real-typing UX parity;
        // wiring both is idempotent (see TileNotional's identical comment).
        onInput={(e: InputChangeEvent): void => {
          setValue(e.currentTarget.value);
        }}
        onChange={(e: InputChangeEvent): void => {
          setValue(e.currentTarget.value);
        }}
        class={styles.input}
      />
      <Show when={comparator() === "inRange"}>
        <input
          type="date"
          data-testid="date-filter-value-to"
          value={valueTo()}
          onInput={(e: InputChangeEvent): void => {
            setValueTo(e.currentTarget.value);
          }}
          onChange={(e: InputChangeEvent): void => {
            setValueTo(e.currentTarget.value);
          }}
          class={styles.input}
        />
      </Show>
      <div class={styles.buttons}>
        <button
          type="button"
          data-testid="date-filter-apply"
          onClick={handleApply}
          class={styles.applyBtn}
        >
          Apply
        </button>
        <button
          type="button"
          onClick={() => {
            props.onApply(null);
          }}
          class={styles.resetBtn}
        >
          Reset
        </button>
      </div>
    </div>
  );
}

interface DateFilterProps<TRow> {
  column: keyof TRow;
  currentFilter: ColumnFilter<TRow> | undefined;
  onApply: (filter: ColumnFilter<TRow> | null) => void;
}

type SelectChangeEvent = Event & { currentTarget: HTMLSelectElement };
type InputChangeEvent = Event & { currentTarget: HTMLInputElement };

interface ComparatorOption {
  value: Comparator;
  label: string;
}

const comparators: ComparatorOption[] = [
  { value: "eq", label: "Equals" },
  { value: "neq", label: "Not equal" },
  { value: "lt", label: "Less than" },
  { value: "lte", label: "Less than or equals" },
  { value: "gt", label: "Greater than" },
  { value: "gte", label: "Greater than or equals" },
  { value: "inRange", label: "In range" },
];
