// packages/client-react/src/ui/fx/blotter/columnFilter/NumberFilter.tsx
import type { ChangeEvent, ReactElement } from "react";
import { useState } from "react";

import type { ColumnFilter, Comparator } from "@rtc/client-core";

import styles from "./NumberFilter.module.css";

export function NumberFilter<TRow>({
  column,
  currentFilter,
  onApply,
}: NumberFilterProps<TRow>): ReactElement {
  const [comparator, setComparator] = useState<Comparator>(
    currentFilter?.type === "number" ? currentFilter.comparator : "eq",
  );

  const [value, setValue] = useState(
    currentFilter?.type === "number" ? String(currentFilter.value) : "",
  );

  const [valueTo, setValueTo] = useState(
    currentFilter?.type === "number" && currentFilter.valueTo != null
      ? String(currentFilter.valueTo)
      : "",
  );

  function applyNumberFilter(): void {
    const num = parseFloat(value);

    if (Number.isNaN(num)) {
      onApply(null);
      return;
    }

    const numTo = comparator === "inRange" ? parseFloat(valueTo) : undefined;
    onApply({
      type: "number",
      column,
      comparator,
      value: num,
      valueTo: numTo !== undefined && !Number.isNaN(numTo) ? numTo : undefined,
    });
  }

  return (
    <div className={styles.container}>
      <select
        data-testid="number-filter-comparator"
        value={comparator}
        onChange={(e: ChangeEvent<HTMLSelectElement>): void => {
          setComparator(e.target.value as Comparator);
        }}
        className={styles.select}
      >
        {comparators.map((c) => {
          return (
            <option key={c.value} value={c.value}>
              {c.label}
            </option>
          );
        })}
      </select>
      <input
        type="number"
        data-testid="number-filter-value"
        value={value}
        onChange={(e: ChangeEvent<HTMLInputElement>): void => {
          setValue(e.target.value);
        }}
        placeholder="Value"
        className={styles.input}
      />
      {comparator === "inRange" && (
        <input
          type="number"
          data-testid="number-filter-value-to"
          value={valueTo}
          onChange={(e: ChangeEvent<HTMLInputElement>): void => {
            setValueTo(e.target.value);
          }}
          placeholder="To"
          className={styles.input}
        />
      )}
      <div className={styles.buttons}>
        <button
          type="button"
          data-testid="number-filter-apply"
          onClick={applyNumberFilter}
          className={styles.applyBtn}
        >
          Apply
        </button>
        <button
          type="button"
          onClick={() => {
            return onApply(null);
          }}
          className={styles.resetBtn}
        >
          Reset
        </button>
      </div>
    </div>
  );
}

interface NumberFilterProps<TRow> {
  column: keyof TRow;
  currentFilter: ColumnFilter<TRow> | undefined;
  onApply: (filter: ColumnFilter<TRow> | null) => void;
}

interface ComparatorOption {
  value: Comparator;
  label: string;
}

const comparators: ComparatorOption[] = [
  { value: "eq", label: "Equals" },
  { value: "neq", label: "Not equal" },
  { value: "lt", label: "Less than" },
  { value: "lte", label: "Less than or equals" },
  { value: "gt", label: "Greater than" },
  { value: "gte", label: "Greater than or equals" },
  { value: "inRange", label: "In range" },
];

// packages/client-solid/src/ui/fx/blotter/columnFilter/NumberFilter.tsx
import type { JSX } from "solid-js";
import { createSignal, For, Show } from "solid-js";

import type { ColumnFilter, Comparator } from "@rtc/client-core";

import styles from "./NumberFilter.module.css";

export function NumberFilter<TRow>(
  props: NumberFilterProps<TRow>,
): JSX.Element {
  const [comparator, setComparator] = createSignal<Comparator>(
    props.currentFilter?.type === "number"
      ? props.currentFilter.comparator
      : "eq",
  );
  const [value, setValue] = createSignal(
    props.currentFilter?.type === "number"
      ? String(props.currentFilter.value)
      : "",
  );
  const [valueTo, setValueTo] = createSignal(
    props.currentFilter?.type === "number" &&
      props.currentFilter.valueTo != null
      ? String(props.currentFilter.valueTo)
      : "",
  );

  function handleApply(): void {
    const num = Number.parseFloat(value());

    if (Number.isNaN(num)) {
      props.onApply(null);
      return;
    }

    const numTo =
      comparator() === "inRange" ? Number.parseFloat(valueTo()) : undefined;
    props.onApply({
      type: "number",
      column: props.column,
      comparator: comparator(),
      value: num,
      valueTo: numTo !== undefined && !Number.isNaN(numTo) ? numTo : undefined,
    });
  }

  return (
    <div class={styles.container}>
      <select
        data-testid="number-filter-comparator"
        value={comparator()}
        onChange={(e: SelectChangeEvent): void => {
          setComparator(e.currentTarget.value as Comparator);
        }}
        class={styles.select}
      >
        <For each={comparators}>
          {(c: ComparatorOption) => {
            return <option value={c.value}>{c.label}</option>;
          }}
        </For>
      </select>
      <input
        type="number"
        data-testid="number-filter-value"
        value={value()}
        // React's onChange fires per keystroke (native `input` event);
        // Solid's onChange maps to native `change` only (fires on blur) —
        // both wired here so real typing (`input`) and a programmatic
        // `change` dispatch both narrow live (wiring both is idempotent,
        // see TileNotional's identical comment).
        onInput={(e: InputChangeEvent): void => {
          setValue(e.currentTarget.value);
        }}
        onChange={(e: InputChangeEvent): void => {
          setValue(e.currentTarget.value);
        }}
        placeholder="Value"
        class={styles.input}
      />
      <Show when={comparator() === "inRange"}>
        <input
          type="number"
          data-testid="number-filter-value-to"
          value={valueTo()}
          onInput={(e: InputChangeEvent): void => {
            setValueTo(e.currentTarget.value);
          }}
          onChange={(e: InputChangeEvent): void => {
            setValueTo(e.currentTarget.value);
          }}
          placeholder="To"
          class={styles.input}
        />
      </Show>
      <div class={styles.buttons}>
        <button
          type="button"
          data-testid="number-filter-apply"
          onClick={handleApply}
          class={styles.applyBtn}
        >
          Apply
        </button>
        <button
          type="button"
          onClick={() => {
            props.onApply(null);
          }}
          class={styles.resetBtn}
        >
          Reset
        </button>
      </div>
    </div>
  );
}

interface NumberFilterProps<TRow> {
  column: keyof TRow;
  currentFilter: ColumnFilter<TRow> | undefined;
  onApply: (filter: ColumnFilter<TRow> | null) => void;
}

type SelectChangeEvent = Event & { currentTarget: HTMLSelectElement };
type InputChangeEvent = Event & { currentTarget: HTMLInputElement };

interface ComparatorOption {
  value: Comparator;
  label: string;
}

const comparators: ComparatorOption[] = [
  { value: "eq", label: "Equals" },
  { value: "neq", label: "Not equal" },
  { value: "lt", label: "Less than" },
  { value: "lte", label: "Less than or equals" },
  { value: "gt", label: "Greater than" },
  { value: "gte", label: "Greater than or equals" },
  { value: "inRange", label: "In range" },
];
