// packages/client/src/fx/liveRates/CurrencyFilter.tsx
import { CURRENCY_CATEGORIES, type CurrencyCategory } from "@rtc/domain";

interface CurrencyFilterProps {
  selected: CurrencyCategory;
  onChange: (category: CurrencyCategory) => void;
}

export function CurrencyFilter({ selected, onChange }: CurrencyFilterProps) {
  return (
    <div data-testid="currency-filter" style={{ display: "flex", gap: 2 }}>
      {CURRENCY_CATEGORIES.map((cat) => (
        <button
          key={cat}
          data-testid={`filter-${cat}`}
          onClick={() => onChange(cat)}
          style={{
            padding: "4px 10px",
            fontSize: 12,
            border: "none",
            borderRadius: 3,
            cursor: "pointer",
            fontWeight: selected === cat ? 600 : 400,
            backgroundColor:
              selected === cat
                ? "var(--accent-primary)"
                : "transparent",
            color:
              selected === cat
                ? "#fff"
                : "var(--text-secondary)",
            transition: "background-color 0.15s, color 0.15s",
          }}
        >
          {cat}
        </button>
      ))}
    </div>
  );
}

// packages/client-solid/src/ui/fx/liveRates/CurrencyFilter.tsx
import type { JSX } from "solid-js";
import { For } from "solid-js";

import { CURRENCY_CATEGORIES, type CurrencyCategory } from "@rtc/domain";

import styles from "./CurrencyFilter.module.css";

export function CurrencyFilter(props: CurrencyFilterProps): JSX.Element {
  return (
    <div data-testid="currency-filter" class={styles.filterBar}>
      <span class={styles.label}>FILTER</span>
      <For each={CURRENCY_CATEGORIES}>
        {(cat: CurrencyCategory) => {
          return (
            <button
              type="button"
              data-testid={`filter-${cat}`}
              data-active={props.selected === cat ? "true" : "false"}
              onClick={() => {
                props.onChange(cat);
              }}
              class={styles.chip}
            >
              {cat}
            </button>
          );
        }}
      </For>
    </div>
  );
}

interface CurrencyFilterProps {
  selected: CurrencyCategory;
  onChange: (category: CurrencyCategory) => void;
}
