// packages/client-react/src/ui/shell/chrome/ThemePicker.tsx
import type { CSSProperties, ReactElement } from "react";
import { useEffect, useRef, useState } from "react";

import { THEME_SKINS, type ThemeSkin } from "@rtc/domain";

import { ThemeToggle } from "../theme/ThemeToggle";
import { themeTokens } from "../theme/tokens";
import { useTheme } from "../theme/useTheme";

import styles from "./ThemePicker.module.css";

/**
 * Theme picker — composes the REUSED `ThemeToggle` (the light/dark mode
 * control, which carries the `theme-toggle` testid + aria-label the e2e theme
 * scenario pins) with a compact skin dropdown over `THEME_SKINS` (PROTO
 * Reactive Trader.dc.html:155-166). Both write through the real theme seam
 * (`useTheme().setSkin` + `ThemeToggle`'s `cycleMode`), so the ThemeProvider
 * repaints `:root` and `document.documentElement.dataset.{skin,mode}`.
 *
 * The trigger (`skin-picker` testid) shows the active skin's two-swatch chip
 * + name; opening it reveals a "THEME" popover listing every skin as a
 * `role="option"` row (`data-skin` + `data-active`, ported from the old
 * segmented-buttons markup so the UI-contract page object keeps working
 * unchanged) with a checkmark on the active row. The open/close idiom follows
 * AccountMenu/NotificationsMenu's local `open` state + trigger click, extended
 * with outside-click + Escape to close — the compact dropdown, unlike the old
 * always-visible segmented row, needs an explicit dismissal path.
 */
export function ThemePicker(): ReactElement {
  const { skin, setSkin, mode } = useTheme();
  const [open, setOpen] = useState(false);
  const anchorRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!open) {
      return undefined;
    }

    function closePickerOnOutsideClick(event: MouseEvent): void {
      if (!anchorRef.current?.contains(event.target as Node)) {
        setOpen(false);
      }
    }

    function closePickerOnEscape(event: KeyboardEvent): void {
      if (event.key === "Escape") {
        setOpen(false);
      }
    }

    document.addEventListener("mousedown", closePickerOnOutsideClick);
    document.addEventListener("keydown", closePickerOnEscape);

    return () => {
      document.removeEventListener("mousedown", closePickerOnOutsideClick);
      document.removeEventListener("keydown", closePickerOnEscape);
    };
  }, [open]);

  function selectSkin(next: ThemeSkin): void {
    setSkin(next);
    setOpen(false);
  }

  function selectSkinFor(next: ThemeSkin) {
    return () => {
      selectSkin(next);
    };
  }

  function toggleThemePicker(): void {
    setOpen((prev) => {
      return !prev;
    });
  }

  const activeTokens = themeTokens[skin][mode];

  return (
    <div className={styles.picker}>
      <ThemeToggle />
      <div className={styles.anchor} ref={anchorRef}>
        <button
          type="button"
          data-testid="skin-picker"
          aria-haspopup="listbox"
          aria-expanded={open}
          aria-label="Theme skin"
          className={styles.trigger}
          onClick={toggleThemePicker}
          style={
            // eslint-disable-next-line no-restricted-syntax -- runtime theme swatch colors via CSS custom properties; static CSS can't express them
            {
              "--swatch-1": activeTokens["--accent-primary"],
              "--swatch-2": activeTokens["--accent-2"],
            } as CSSProperties
          }
        >
          <span className={styles.swatches}>
            <span className={styles.swatchA} />
            <span className={styles.swatchB} />
          </span>
          <span className={styles.skinName}>{SKIN_LABEL[skin]}</span>
          <span className={styles.caret}>▾</span>
        </button>
        {open ? (
          <div className={styles.menu} role="listbox" aria-label="Theme skin">
            <span className={styles.heading}>THEME</span>
            {THEME_SKINS.map((s) => {
              const tokens = themeTokens[s][mode];
              const active = s === skin;
              return (
                <button
                  key={s}
                  type="button"
                  role="option"
                  aria-selected={active}
                  data-skin={s}
                  data-active={active ? "true" : "false"}
                  className={styles.skinRow}
                  onClick={selectSkinFor(s)}
                  style={
                    // eslint-disable-next-line no-restricted-syntax -- runtime theme swatch colors via CSS custom properties; static CSS can't express them
                    {
                      "--swatch-1": tokens["--accent-primary"],
                      "--swatch-2": tokens["--accent-2"],
                    } as CSSProperties
                  }
                >
                  <span className={styles.swatches}>
                    <span className={styles.swatchA} />
                    <span className={styles.swatchB} />
                  </span>
                  <span className={styles.skinName}>{SKIN_LABEL[s]}</span>
                  <span className={styles.mark}>{active ? "✓" : ""}</span>
                </button>
              );
            })}
          </div>
        ) : null}
      </div>
    </div>
  );
}

/** Display label per skin, rendered proper-case exactly as written (PROTO
 *  shellData.ts `themeNames`, e.g. "Holo HUD ▾" — no CSS uppercasing).
 *  "Classic" is app-only; the rest match the prototype verbatim. */
const SKIN_LABEL: Record<ThemeSkin, string> = {
  classic: "Classic",
  holo: "Holo HUD",
  holo3d: "Holo HUD 3D",
  terminal: "Terminal",
  terminal3d: "Terminal 3D",
  neon: "Neon Grid",
};

// packages/client-solid/src/ui/shell/chrome/ThemePicker.tsx
import {
  createEffect,
  createSignal,
  For,
  type JSX,
  onCleanup,
  Show,
} from "solid-js";

import { THEME_SKINS, type ThemeSkin } from "@rtc/domain";

import { ThemeToggle } from "../theme/ThemeToggle";
import { themeTokens } from "../theme/tokens";
import { useTheme } from "../theme/useTheme";

import styles from "./ThemePicker.module.css";

/**
 * Theme picker — composes the REUSED `ThemeToggle` (the light/dark mode
 * control, which carries the `theme-toggle` testid + aria-label the e2e theme
 * scenario pins) with a compact skin dropdown over `THEME_SKINS` (PROTO
 * Reactive Trader.dc.html:155-166). Both write through the real theme seam
 * (`useTheme().setSkin` + `ThemeToggle`'s `cycleMode`), so the ThemeProvider
 * repaints `:root` and `document.documentElement.dataset.{skin,mode}`.
 *
 * The trigger (`skin-picker` testid) shows the active skin's two-swatch chip
 * + name; opening it reveals a "THEME" popover listing every skin as a
 * `role="option"` row (`data-skin` + `data-active`, ported from the old
 * segmented-buttons markup so the UI-contract page object keeps working
 * unchanged) with a checkmark on the active row. The open/close idiom follows
 * AccountMenu/NotificationsMenu's local `open` state + trigger click, extended
 * with outside-click + Escape to close — the compact dropdown, unlike the old
 * always-visible segmented row, needs an explicit dismissal path.
 */
export function ThemePicker(): JSX.Element {
  const { skin, setSkin, mode } = useTheme();
  const [open, setOpen] = createSignal(false);
  let anchorEl!: HTMLDivElement;

  createEffect(() => {
    if (!open()) {
      return;
    }

    function closePickerOnOutsideClick(event: MouseEvent): void {
      if (!anchorEl.contains(event.target as Node)) {
        setOpen(false);
      }
    }

    function closePickerOnEscape(event: KeyboardEvent): void {
      if (event.key === "Escape") {
        setOpen(false);
      }
    }

    document.addEventListener("mousedown", closePickerOnOutsideClick);
    document.addEventListener("keydown", closePickerOnEscape);

    onCleanup(() => {
      document.removeEventListener("mousedown", closePickerOnOutsideClick);
      document.removeEventListener("keydown", closePickerOnEscape);
    });
  });

  function selectSkin(next: ThemeSkin): void {
    setSkin(next);
    setOpen(false);
  }

  function selectSkinFor(next: ThemeSkin) {
    return () => {
      selectSkin(next);
    };
  }

  function toggleThemePicker(): void {
    setOpen(!open());
  }

  return (
    <div class={styles.picker}>
      <ThemeToggle />
      <div class={styles.anchor} ref={anchorEl}>
        <button
          type="button"
          data-testid="skin-picker"
          aria-haspopup="listbox"
          aria-expanded={open()}
          aria-label="Theme skin"
          class={styles.trigger}
          onClick={toggleThemePicker}
          style={
            // eslint-disable-next-line no-restricted-syntax -- runtime theme swatch colors via CSS custom properties; static CSS can't express them
            {
              "--swatch-1": themeTokens[skin()][mode()]["--accent-primary"],
              "--swatch-2": themeTokens[skin()][mode()]["--accent-2"],
            }
          }
        >
          <span class={styles.swatches}>
            <span class={styles.swatchA} />
            <span class={styles.swatchB} />
          </span>
          <span class={styles.skinName}>{SKIN_LABEL[skin()]}</span>
          <span class={styles.caret}>▾</span>
        </button>
        <Show when={open()}>
          <div class={styles.menu} role="listbox" aria-label="Theme skin">
            <span class={styles.heading}>THEME</span>
            <For each={THEME_SKINS}>
              {(s: ThemeSkin) => {
                function active(): boolean {
                  return s === skin();
                }

                return (
                  <button
                    type="button"
                    role="option"
                    aria-selected={active()}
                    data-skin={s}
                    data-active={active() ? "true" : "false"}
                    class={styles.skinRow}
                    onClick={selectSkinFor(s)}
                    style={
                      // eslint-disable-next-line no-restricted-syntax -- runtime theme swatch colors via CSS custom properties; static CSS can't express them
                      {
                        "--swatch-1":
                          themeTokens[s][mode()]["--accent-primary"],
                        "--swatch-2": themeTokens[s][mode()]["--accent-2"],
                      }
                    }
                  >
                    <span class={styles.swatches}>
                      <span class={styles.swatchA} />
                      <span class={styles.swatchB} />
                    </span>
                    <span class={styles.skinName}>{SKIN_LABEL[s]}</span>
                    <span class={styles.mark}>{active() ? "✓" : ""}</span>
                  </button>
                );
              }}
            </For>
          </div>
        </Show>
      </div>
    </div>
  );
}

/** Display label per skin, rendered proper-case exactly as written (PROTO
 *  shellData.ts `themeNames`, e.g. "Holo HUD ▾" — no CSS uppercasing).
 *  "Classic" is app-only; the rest match the prototype verbatim. */
const SKIN_LABEL: Record<ThemeSkin, string> = {
  classic: "Classic",
  holo: "Holo HUD",
  holo3d: "Holo HUD 3D",
  terminal: "Terminal",
  terminal3d: "Terminal 3D",
  neon: "Neon Grid",
};
