// packages/client-react-native/src/ui/credit/sellSide/TradeTicket.tsx
import type { JSX } from "react";
import { useState } from "react";
import {
  Pressable,
  StyleSheet,
  Text,
  TextInput,
  type TextStyle,
  View,
  type ViewStyle,
} from "react-native";

import { type Instrument, type Quote, type Rfq, RfqState } from "@rtc/domain";
import { useViewModel } from "@rtc/react-bindings";

import type { RnTheme } from "#/ui/theme/tokens";
import { useThemedStyles } from "#/ui/theme/useThemedStyles";

interface TradeTicketProps {
  rfq: Rfq;
  quote: Quote;
  instrument: Instrument | undefined;
}

export function TradeTicket({
  rfq,
  quote,
  instrument,
}: TradeTicketProps): JSX.Element {
  const { useTicketSubmission } = useViewModel();
  const ticket = useTicketSubmission();
  const { submitPrice, pass } = ticket;
  const [price, setPrice] = useState("");
  const styles = useThemedStyles(makeStyles);
  const submitted = ticket.state.submitted;

  const isActive =
    rfq.state === RfqState.Open && quote.state.type === "pendingWithoutPrice";
  const hasResponded = quote.state.type !== "pendingWithoutPrice";

  function handleSubmit(): void {
    const num = parseFloat(price);

    if (Number.isNaN(num) || num <= 0) {
      return;
    }

    submitPrice(quote.id, num);
  }

  function handlePass(): void {
    pass(quote.id);
  }

  return (
    <View style={styles.ticket} testID={`sell-ticket-${rfq.id}`}>
      <View style={styles.info}>
        <Text style={styles.instrumentName}>
          {instrument?.name ?? `Instrument #${rfq.instrumentId}`}
        </Text>
        <Text style={styles.instrumentMeta}>
          {instrument?.cusip} | {rfq.direction} | Qty:{" "}
          {rfq.quantity.toLocaleString()}
        </Text>
      </View>

      {hasResponded || submitted ? (
        <Text style={styles.respondedText}>{respondedLabel(rfq, quote)}</Text>
      ) : isActive ? (
        <View style={styles.inputRow}>
          <TextInput
            testID={`sell-ticket-price-${rfq.id}`}
            keyboardType="numeric"
            value={price}
            onChangeText={setPrice}
            placeholder="Price"
            placeholderTextColor={styles.placeholder.color}
            style={styles.priceInput}
          />
          <Pressable
            testID={`sell-ticket-submit-${rfq.id}`}
            disabled={!price}
            style={price ? styles.submitBtn : styles.submitBtnDisabled}
            onPress={handleSubmit}
          >
            <Text style={styles.btnLabel}>Submit</Text>
          </Pressable>
          <Pressable
            testID={`sell-ticket-pass-${rfq.id}`}
            style={styles.passBtn}
            onPress={handlePass}
          >
            <Text style={styles.btnLabel}>Pass</Text>
          </Pressable>
        </View>
      ) : (
        <Text style={styles.closedText}>{closedLabel(rfq.state)}</Text>
      )}
    </View>
  );
}

function respondedLabel(rfq: Rfq, quote: Quote): string {
  if (quote.state.type === "passed") {
    return "Passed";
  }

  if (quote.state.type === "pendingWithPrice") {
    return `Quoted: $${quote.state.price}`;
  }

  if (rfq.state === RfqState.Cancelled) {
    return "RFQ Cancelled";
  }

  if (rfq.state === RfqState.Expired) {
    return "RFQ Expired";
  }

  return "Responded";
}

function closedLabel(state: RfqState): string {
  if (state === RfqState.Cancelled) {
    return "Cancelled";
  }

  if (state === RfqState.Expired) {
    return "Expired";
  }

  return "Closed";
}

interface TradeTicketStyles {
  ticket: ViewStyle;
  info: ViewStyle;
  instrumentName: TextStyle;
  instrumentMeta: TextStyle;
  respondedText: TextStyle;
  closedText: TextStyle;
  inputRow: ViewStyle;
  priceInput: TextStyle;
  placeholder: TextStyle;
  submitBtn: ViewStyle;
  submitBtnDisabled: ViewStyle;
  passBtn: ViewStyle;
  btnLabel: TextStyle;
}

function makeStyles(t: RnTheme): TradeTicketStyles {
  return StyleSheet.create({
    ticket: {
      gap: 8,
      padding: 12,
      marginHorizontal: 8,
      marginVertical: 4,
      borderRadius: 8,
      backgroundColor: t.panel,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: t.border,
    },
    info: { gap: 2 },
    instrumentName: {
      fontSize: 14,
      fontWeight: "600",
      color: t.textPrimary,
      fontFamily: t.fontDisplay,
    },
    instrumentMeta: {
      fontSize: 12,
      color: t.textMuted,
      fontFamily: t.fontMono,
    },
    respondedText: {
      fontSize: 13,
      color: t.textSecondary,
      fontFamily: t.fontDisplay,
    },
    closedText: { fontSize: 13, color: t.textMuted, fontFamily: t.fontDisplay },
    inputRow: { flexDirection: "row", alignItems: "center", gap: 8 },
    priceInput: {
      flex: 1,
      borderWidth: 1,
      borderColor: t.border,
      borderRadius: 6,
      padding: 8,
      color: t.textPrimary,
      fontFamily: t.fontMono,
    },
    placeholder: { color: t.textMuted },
    submitBtn: {
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 6,
      backgroundColor: t.accentPositive,
    },
    submitBtnDisabled: {
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 6,
      backgroundColor: t.bgSecondary,
      opacity: 0.5,
    },
    passBtn: {
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 6,
      backgroundColor: t.bgSecondary,
    },
    btnLabel: {
      fontSize: 12,
      color: t.textOnAccent,
      fontFamily: t.fontDisplay,
    },
  });
}

// packages/client-solid/src/ui/credit/sellSide/TradeTicket.tsx
import type { JSX } from "solid-js";
import { createMemo, createSignal, Show } from "solid-js";

import { type Instrument, type Quote, type Rfq, RfqState } from "@rtc/domain";
import { useViewModel } from "@rtc/solid-bindings";

import styles from "./TradeTicket.module.css";

export function TradeTicket(props: TradeTicketProps): JSX.Element {
  const { useTicketSubmission, useAnimationIntents } = useViewModel();
  // App-layer machine: submit-price / pass flow + the submitted flag. The
  // component keeps only the price draft + parseFloat guard below.
  const anim = useAnimationIntents(`rfq:${props.rfq.id}`);
  const ticket = useTicketSubmission();
  const { submitPrice, pass } = ticket;
  const [price, setPrice] = createSignal("");

  const isActive = createMemo((): boolean => {
    return (
      props.rfq.state === RfqState.Open &&
      props.quote.state.type === "pendingWithoutPrice"
    );
  });
  const hasResponded = createMemo((): boolean => {
    return props.quote.state.type !== "pendingWithoutPrice";
  });
  const animKind = createMemo((): "fill" | undefined => {
    return anim()?.kind === "fill" ? "fill" : undefined;
  });
  const submitted = createMemo((): boolean => {
    return ticket.state().submitted;
  });

  function handleSubmit(): void {
    const num = Number.parseFloat(price());

    if (Number.isNaN(num) || num <= 0) {
      return;
    }

    submitPrice(props.quote.id, num);
  }

  function handlePass(): void {
    pass(props.quote.id);
  }

  // React's onChange fires on every keystroke (native `input` event);
  // Solid's onChange maps to the native `change` event only (fires on
  // blur/commit) — both wired to this one handler so real typing (`input`,
  // what @testing-library/user-event's type() dispatches) and a
  // programmatic `change` both narrow live (mirrors QuickFilter.tsx).
  function handlePriceEdit(e: InputChangeEvent): void {
    setPrice(e.currentTarget.value);
  }

  return (
    <div
      class={styles.ticket}
      data-active={props.rfq.state === RfqState.Open ? "true" : "false"}
      data-anim={animKind()}
    >
      <div>
        <div class={styles.instrumentName}>
          {props.instrument?.name ?? `Instrument #${props.rfq.instrumentId}`}
        </div>
        <div class={styles.instrumentMeta}>
          {props.instrument?.cusip} | {props.rfq.direction} | Qty:{" "}
          {props.rfq.quantity.toLocaleString()}
        </div>
      </div>

      <Show
        when={hasResponded() || submitted()}
        fallback={
          <Show
            when={isActive()}
            fallback={
              <div class={styles.closedText}>
                {props.rfq.state === RfqState.Cancelled
                  ? "Cancelled"
                  : props.rfq.state === RfqState.Expired
                    ? "Expired"
                    : "Closed"}
              </div>
            }
          >
            <div class={styles.inputRow}>
              <input
                type="number"
                data-testid="trade-ticket-price"
                value={price()}
                onInput={handlePriceEdit}
                onChange={handlePriceEdit}
                placeholder="Price"
                class={styles.priceInput}
              />
              <button
                type="button"
                onClick={handleSubmit}
                disabled={!price()}
                data-can-submit={price() ? "true" : "false"}
                class={styles.submitBtn}
              >
                Submit
              </button>
              <button type="button" onClick={handlePass} class={styles.passBtn}>
                Pass
              </button>
            </div>
          </Show>
        }
      >
        <div class={styles.respondedText}>
          {props.quote.state.type === "passed"
            ? "Passed"
            : props.quote.state.type === "pendingWithPrice"
              ? `Quoted: $${props.quote.state.price}`
              : props.rfq.state === RfqState.Cancelled
                ? "RFQ Cancelled"
                : props.rfq.state === RfqState.Expired
                  ? "RFQ Expired"
                  : "Responded"}
        </div>
      </Show>
    </div>
  );
}

interface TradeTicketProps {
  rfq: Rfq;
  quote: Quote;
  instrument: Instrument | undefined;
}

type InputChangeEvent = Event & { currentTarget: HTMLInputElement };
