// packages/client/src/ui/credit/sellSide/TradeTicket.tsx
import { useCallback, useState } from "react";
import { type Rfq, type Quote, type Instrument, RfqState } from "@rtc/domain";
import { useHooks } from "../../hooks/HooksProvider";

interface TradeTicketProps {
  rfq: Rfq;
  quote: Quote;
  instrument: Instrument | undefined;
}

export function TradeTicket({ rfq, quote, instrument }: TradeTicketProps) {
  const hooks = useHooks();
  // App-layer machine: submit-price / pass flow + the submitted flag. The
  // component keeps only the price draft + parseFloat guard below.
  const ticket = hooks.useTicketSubmission();
  const { submitPrice, pass } = ticket;
  const [price, setPrice] = useState("");
  const submitted = ticket.state.submitted;

  const isActive = rfq.state === RfqState.Open && quote.state.type === "pendingWithoutPrice";
  const hasResponded = quote.state.type !== "pendingWithoutPrice";

  const handleSubmit = useCallback(() => {
    const num = parseFloat(price);
    if (isNaN(num) || num <= 0) return;
    submitPrice(quote.id, num);
  }, [submitPrice, quote.id, price]);

  const handlePass = useCallback(() => {
    pass(quote.id);
  }, [pass, quote.id]);

  return (
    <div style={{
      backgroundColor: "var(--bg-tile)",
      border: "1px solid var(--border-primary)",
      borderRadius: 6,
      padding: 12,
      display: "flex",
      flexDirection: "column",
      gap: 6,
      opacity: rfq.state !== RfqState.Open ? 0.6 : 1,
    }}>
      <div>
        <div style={{ fontSize: 13, fontWeight: 600, color: "var(--text-primary)" }}>
          {instrument?.name ?? `Instrument #${rfq.instrumentId}`}
        </div>
        <div style={{ fontSize: 10, color: "var(--text-muted)" }}>
          {instrument?.cusip} | {rfq.direction} | Qty: {rfq.quantity.toLocaleString()}
        </div>
      </div>

      {hasResponded || submitted ? (
        <div style={{ fontSize: 12, color: "var(--text-secondary)", padding: "4px 0" }}>
          {quote.state.type === "passed" ? "Passed" :
           quote.state.type === "pendingWithPrice" ? `Quoted: $${quote.state.price}` :
           rfq.state === RfqState.Cancelled ? "RFQ Cancelled" :
           rfq.state === RfqState.Expired ? "RFQ Expired" :
           "Responded"}
        </div>
      ) : isActive ? (
        <div style={{ display: "flex", gap: 4, alignItems: "center" }}>
          <input
            type="number"
            data-testid="trade-ticket-price"
            value={price}
            onChange={(e) => setPrice(e.target.value)}
            placeholder="Price"
            style={{
              flex: 1,
              padding: "4px 6px",
              fontSize: 12,
              border: "1px solid var(--border-primary)",
              borderRadius: 3,
              backgroundColor: "transparent",
              color: "var(--text-primary)",
              outline: "none",
            }}
          />
          <button
            onClick={handleSubmit}
            disabled={!price}
            style={{
              padding: "4px 10px",
              fontSize: 11,
              fontWeight: 600,
              border: "none",
              borderRadius: 3,
              backgroundColor: "var(--accent-positive)",
              color: "#fff",
              cursor: price ? "pointer" : "not-allowed",
              opacity: price ? 1 : 0.5,
            }}
          >
            Submit
          </button>
          <button
            onClick={handlePass}
            style={{
              padding: "4px 10px",
              fontSize: 11,
              border: "1px solid var(--border-primary)",
              borderRadius: 3,
              backgroundColor: "transparent",
              color: "var(--text-secondary)",
              cursor: "pointer",
            }}
          >
            Pass
          </button>
        </div>
      ) : (
        <div style={{ fontSize: 12, color: "var(--text-muted)" }}>
          {rfq.state === RfqState.Cancelled ? "Cancelled" : rfq.state === RfqState.Expired ? "Expired" : "Closed"}
        </div>
      )}
    </div>
  );
}

// packages/client-solid/src/ui/credit/sellSide/TradeTicket.tsx
import type { JSX } from "solid-js";
import { createMemo, createSignal, Show } from "solid-js";

import { type Instrument, type Quote, type Rfq, RfqState } from "@rtc/domain";
import { useViewModel } from "@rtc/solid-bindings";

import styles from "./TradeTicket.module.css";

export function TradeTicket(props: TradeTicketProps): JSX.Element {
  const { useTicketSubmission, useAnimationIntents } = useViewModel();
  // App-layer machine: submit-price / pass flow + the submitted flag. The
  // component keeps only the price draft + parseFloat guard below.
  const anim = useAnimationIntents(`rfq:${props.rfq.id}`);
  const ticket = useTicketSubmission();
  const { submitPrice, pass } = ticket;
  const [price, setPrice] = createSignal("");

  const isActive = createMemo((): boolean => {
    return (
      props.rfq.state === RfqState.Open &&
      props.quote.state.type === "pendingWithoutPrice"
    );
  });
  const hasResponded = createMemo((): boolean => {
    return props.quote.state.type !== "pendingWithoutPrice";
  });
  const animKind = createMemo((): "fill" | undefined => {
    return anim()?.kind === "fill" ? "fill" : undefined;
  });
  const submitted = createMemo((): boolean => {
    return ticket.state().submitted;
  });

  function handleSubmit(): void {
    const num = Number.parseFloat(price());

    if (Number.isNaN(num) || num <= 0) {
      return;
    }

    submitPrice(props.quote.id, num);
  }

  function handlePass(): void {
    pass(props.quote.id);
  }

  // React's onChange fires on every keystroke (native `input` event);
  // Solid's onChange maps to the native `change` event only (fires on
  // blur/commit) — both wired to this one handler so real typing (`input`,
  // what @testing-library/user-event's type() dispatches) and a
  // programmatic `change` both narrow live (mirrors QuickFilter.tsx).
  function handlePriceEdit(e: InputChangeEvent): void {
    setPrice(e.currentTarget.value);
  }

  return (
    <div
      class={styles.ticket}
      data-active={props.rfq.state === RfqState.Open ? "true" : "false"}
      data-anim={animKind()}
    >
      <div>
        <div class={styles.instrumentName}>
          {props.instrument?.name ?? `Instrument #${props.rfq.instrumentId}`}
        </div>
        <div class={styles.instrumentMeta}>
          {props.instrument?.cusip} | {props.rfq.direction} | Qty:{" "}
          {props.rfq.quantity.toLocaleString()}
        </div>
      </div>

      <Show
        when={hasResponded() || submitted()}
        fallback={
          <Show
            when={isActive()}
            fallback={
              <div class={styles.closedText}>
                {props.rfq.state === RfqState.Cancelled
                  ? "Cancelled"
                  : props.rfq.state === RfqState.Expired
                    ? "Expired"
                    : "Closed"}
              </div>
            }
          >
            <div class={styles.inputRow}>
              <input
                type="number"
                data-testid="trade-ticket-price"
                value={price()}
                onInput={handlePriceEdit}
                onChange={handlePriceEdit}
                placeholder="Price"
                class={styles.priceInput}
              />
              <button
                type="button"
                onClick={handleSubmit}
                disabled={!price()}
                data-can-submit={price() ? "true" : "false"}
                class={styles.submitBtn}
              >
                Submit
              </button>
              <button type="button" onClick={handlePass} class={styles.passBtn}>
                Pass
              </button>
            </div>
          </Show>
        }
      >
        <div class={styles.respondedText}>
          {props.quote.state.type === "passed"
            ? "Passed"
            : props.quote.state.type === "pendingWithPrice"
              ? `Quoted: $${props.quote.state.price}`
              : props.rfq.state === RfqState.Cancelled
                ? "RFQ Cancelled"
                : props.rfq.state === RfqState.Expired
                  ? "RFQ Expired"
                  : "Responded"}
        </div>
      </Show>
    </div>
  );
}

interface TradeTicketProps {
  rfq: Rfq;
  quote: Quote;
  instrument: Instrument | undefined;
}

type InputChangeEvent = Event & { currentTarget: HTMLInputElement };
