// packages/client-react/src/ui/fx/liveRates/tile/TileFooter.tsx
import type { ReactElement } from "react";

import styles from "./TileFooter.module.css";

export function TileFooter({
  spotDate,
  notional,
  baseCurrency,
}: TileFooterProps): ReactElement {
  return (
    <div className={styles.footer}>
      <span className={styles.spotDate}>SPT {spotDate}</span>
      <span className={styles.notional}>
        {notional} {baseCurrency}
      </span>
    </div>
  );
}

interface TileFooterProps {
  spotDate: string;
  notional: string;
  baseCurrency: string;
}

// packages/client-solid/src/ui/fx/liveRates/tile/TileFooter.tsx
import type { JSX } from "solid-js";

import styles from "./TileFooter.module.css";

export function TileFooter(props: TileFooterProps): JSX.Element {
  return (
    <div class={styles.footer}>
      <span class={styles.spotDate}>SPT {props.spotDate}</span>
      <span class={styles.notional}>
        {props.notional} {props.baseCurrency}
      </span>
    </div>
  );
}

interface TileFooterProps {
  spotDate: string;
  notional: string;
  baseCurrency: string;
}
