// packages/client/src/fx/live-rates/tile/tile-price.tsx
import { PriceMovementType, type Price } from "@rtc/domain";

interface TilePriceProps {
  price: Price;
  ratePrecision: number;
  pipsPosition: number;
}

/**
 * Splits a formatted price into parts for big/pip/fractional display.
 * For EURUSD 1.53816 (pipsPosition=4, ratePrecision=5):
 *   prefix="1.53", pips="81", fractional="6"
 */
function splitPrice(
  value: number,
  ratePrecision: number,
  pipsPosition: number,
): { prefix: string; pips: string; fractional: string } {
  const formatted = value.toFixed(ratePrecision);
  const fractionalDigits = ratePrecision - pipsPosition;
  const pipEnd = formatted.length - fractionalDigits;
  const pipStart = pipEnd - 2;

  return {
    prefix: formatted.slice(0, pipStart),
    pips: formatted.slice(pipStart, pipEnd),
    fractional: fractionalDigits > 0 ? formatted.slice(pipEnd) : "",
  };
}

function PriceButton({
  label,
  value,
  ratePrecision,
  pipsPosition,
  movement,
  side,
}: {
  label: string;
  value: number;
  ratePrecision: number;
  pipsPosition: number;
  movement: PriceMovementType;
  side: "bid" | "ask";
}) {
  const { prefix, pips, fractional } = splitPrice(
    value,
    ratePrecision,
    pipsPosition,
  );

  const movementColor =
    movement === PriceMovementType.UP
      ? "var(--accent-positive)"
      : movement === PriceMovementType.DOWN
        ? "var(--accent-negative)"
        : undefined;

  return (
    <button
      style={{
        flex: 1,
        display: "flex",
        flexDirection: "column",
        alignItems: side === "bid" ? "flex-start" : "flex-end",
        padding: "6px 8px",
        background: "none",
        border: "1px solid var(--border-primary)",
        borderRadius: 4,
        cursor: "pointer",
        color: "var(--text-primary)",
        transition: "border-color 0.15s",
      }}
    >
      <span
        style={{ fontSize: 10, color: "var(--text-muted)", marginBottom: 2 }}
      >
        {label}
      </span>
      <span style={{ display: "flex", alignItems: "baseline" }}>
        <span style={{ fontSize: 13, color: "var(--text-secondary)" }}>
          {prefix}
        </span>
        <span
          style={{
            fontSize: 22,
            fontWeight: 700,
            color: movementColor ?? "var(--text-primary)",
          }}
        >
          {pips}
        </span>
        <span
          style={{
            fontSize: 13,
            color: "var(--text-secondary)",
            position: "relative",
            top: -4,
          }}
        >
          {fractional}
        </span>
      </span>
    </button>
  );
}

export function TilePrice({ price, ratePrecision, pipsPosition }: TilePriceProps) {
  return (
    <div style={{ display: "flex", gap: 4 }}>
      <PriceButton
        label="SELL"
        value={price.bid}
        ratePrecision={ratePrecision}
        pipsPosition={pipsPosition}
        movement={price.movementType}
        side="bid"
      />
      <PriceButton
        label="BUY"
        value={price.ask}
        ratePrecision={ratePrecision}
        pipsPosition={pipsPosition}
        movement={price.movementType}
        side="ask"
      />
    </div>
  );
}

export function SpreadDisplay({ spread }: { spread: string }) {
  return (
    <div
      style={{
        textAlign: "center",
        fontSize: 11,
        color: "var(--text-muted)",
        padding: "2px 0",
      }}
    >
      {spread}
    </div>
  );
}

// packages/client-solid/src/ui/fx/liveRates/tile/TilePrice.tsx
import { createMemo, type JSX } from "solid-js";

import { Direction, type Price, PriceMovementType } from "@rtc/domain";

import { SpreadDisplay } from "./SpreadDisplay";

import styles from "./TilePrice.module.css";

export function TilePrice(props: TilePriceProps): JSX.Element {
  return (
    <div class={styles.row}>
      <PriceButton
        value={props.price.bid}
        ratePrecision={props.ratePrecision}
        pipsPosition={props.pipsPosition}
        movement={props.price.movementType}
        side="bid"
        anim={props.anim}
        onExecute={props.onExecute}
        disabled={props.disabled}
      />
      <SpreadDisplay spread={props.spread} />
      <PriceButton
        value={props.price.ask}
        ratePrecision={props.ratePrecision}
        pipsPosition={props.pipsPosition}
        movement={props.price.movementType}
        side="ask"
        anim={props.anim}
        onExecute={props.onExecute}
        disabled={props.disabled}
      />
    </div>
  );
}

interface TilePriceProps {
  price: Price;
  ratePrecision: number;
  pipsPosition: number;
  anim?: "tickUp" | "tickDown";
  spread: string;
  onExecute: (direction: Direction) => void;
  disabled: boolean;
}

interface PriceParts {
  prefix: string;
  pips: string;
  fractional: string;
}

/**
 * Splits a formatted price into parts for big/pip/fractional display.
 * For EURUSD 1.53816 (pipsPosition=4, ratePrecision=5):
 *   prefix="1.53", pips="81", fractional="6"
 */
function splitPrice(
  value: number,
  ratePrecision: number,
  pipsPosition: number,
): PriceParts {
  const formatted = value.toFixed(ratePrecision);
  const fractionalDigits = ratePrecision - pipsPosition;
  const pipEnd = formatted.length - fractionalDigits;
  const pipStart = pipEnd - 2;

  return {
    prefix: formatted.slice(0, pipStart),
    pips: formatted.slice(pipStart, pipEnd),
    fractional: fractionalDigits > 0 ? formatted.slice(pipEnd) : "",
  };
}

function movementKey(movement: PriceMovementType): "up" | "down" | "flat" {
  if (movement === PriceMovementType.UP) {
    return "up";
  }

  if (movement === PriceMovementType.DOWN) {
    return "down";
  }

  return "flat";
}

interface PriceButtonProps {
  value: number;
  ratePrecision: number;
  pipsPosition: number;
  movement: PriceMovementType;
  side: "bid" | "ask";
  anim?: "tickUp" | "tickDown";
  onExecute: (direction: Direction) => void;
  disabled: boolean;
}

function PriceButton(props: PriceButtonProps): JSX.Element {
  const parts = createMemo((): PriceParts => {
    return splitPrice(props.value, props.ratePrecision, props.pipsPosition);
  });

  function executeAtSide(): void {
    props.onExecute(props.side === "bid" ? Direction.Sell : Direction.Buy);
  }

  return (
    <button
      type="button"
      data-testid={props.side === "bid" ? "sell-btn" : "buy-btn"}
      data-side={props.side}
      onClick={executeAtSide}
      disabled={props.disabled}
      class={styles.priceBox}
    >
      <span class={styles.boxLabel}>
        {props.side === "bid" ? "SELL" : "BUY"}
      </span>
      <span class={styles.value}>
        <span class={styles.big}>{parts().prefix}</span>
        <span
          data-testid="tile-pips"
          data-movement={movementKey(props.movement)}
          data-anim={props.anim}
          data-pips={parts().pips}
          class={styles.pips}
        >
          {parts().pips}
        </span>
        <span class={styles.frac}>{parts().fractional}</span>
      </span>
    </button>
  );
}
