// packages/client/src/fx/live-rates/tile/tile-notional.tsx
import { useCallback, useRef, type ChangeEvent, type KeyboardEvent } from "react";
import type { UseNotionalResult } from "../../hooks/use-notional";

interface TileNotionalProps {
  notional: UseNotionalResult;
  baseCurrency: string;
  disabled?: boolean;
}

export function TileNotional({
  notional,
  baseCurrency,
  disabled,
}: TileNotionalProps) {
  const inputRef = useRef<HTMLInputElement>(null);

  const handleChange = useCallback(
    (e: ChangeEvent<HTMLInputElement>) => {
      notional.onChange(e.target.value);
    },
    [notional],
  );

  const handleKeyDown = useCallback(
    (e: KeyboardEvent<HTMLInputElement>) => {
      if (e.key === "Enter") {
        inputRef.current?.blur();
      }
    },
    [],
  );

  const handleFocus = useCallback(() => {
    inputRef.current?.select();
  }, []);

  return (
    <div
      style={{
        display: "flex",
        alignItems: "center",
        gap: 4,
        position: "relative",
      }}
    >
      <span
        style={{
          fontSize: 11,
          color: "var(--text-muted)",
          minWidth: 28,
        }}
      >
        {baseCurrency}
      </span>
      <input
        ref={inputRef}
        value={notional.displayValue}
        onChange={handleChange}
        onKeyDown={handleKeyDown}
        onFocus={handleFocus}
        disabled={disabled}
        style={{
          flex: 1,
          background: "none",
          border: "none",
          borderBottom: `1px solid ${notional.error ? "var(--accent-negative)" : "var(--border-primary)"}`,
          color: "var(--text-primary)",
          fontSize: 13,
          padding: "2px 0",
          outline: "none",
          textAlign: "right",
          fontFamily: "inherit",
        }}
      />
      {!notional.isDefault && (
        <button
          onClick={notional.reset}
          title="Reset to default"
          style={{
            background: "none",
            border: "none",
            color: "var(--text-muted)",
            cursor: "pointer",
            fontSize: 12,
            padding: "0 2px",
            lineHeight: 1,
          }}
        >
          \u21BA
        </button>
      )}
      {notional.error && (
        <span
          style={{
            position: "absolute",
            bottom: -14,
            right: 0,
            fontSize: 10,
            color: "var(--accent-negative)",
          }}
        >
          {notional.error}
        </span>
      )}
    </div>
  );
}

// packages/client-solid/src/ui/fx/liveRates/tile/TileNotional.tsx
import type { Accessor, JSX } from "solid-js";
import { createMemo, Show } from "solid-js";

import type { NotionalIntents, NotionalView } from "@rtc/client-core";

import styles from "./TileNotional.module.css";

export function TileNotional(props: TileNotionalProps): JSX.Element {
  let inputRef!: HTMLInputElement;

  function handleChange(e: InputChangeEvent): void {
    props.notional.change(e.currentTarget.value);
  }

  function handleKeyDown(e: InputKeyDownEvent): void {
    if (e.key === "Enter") {
      inputRef.blur();
    }
  }

  function handleFocus(): void {
    inputRef.select();
  }

  const hasError = createMemo((): boolean => {
    return !!props.notional.state().error;
  });

  return (
    <div class={styles.wrapper}>
      <span class={styles.currencyLabel}>{props.baseCurrency}</span>
      <div class={styles.inputArea}>
        <input
          ref={inputRef}
          value={props.notional.state().displayValue}
          onChange={handleChange}
          onKeyDown={handleKeyDown}
          onFocus={handleFocus}
          disabled={props.disabled}
          data-error={hasError() ? "true" : "false"}
          class={styles.input}
        />
        <Show when={!props.notional.state().isDefault}>
          <button
            type="button"
            onClick={() => {
              props.notional.reset();
            }}
            title="Reset to default"
            class={styles.resetButton}
          >
            {"↺"}
          </button>
        </Show>
      </div>
      <Show when={hasError()}>
        <span class={styles.maxTag}>MAX</span>
      </Show>
      <Show when={hasError()}>
        <span data-testid="notional-error" class={styles.errorMessage}>
          {props.notional.state().error}
        </span>
      </Show>
    </div>
  );
}

interface TileNotionalProps {
  notional: NotionalMachine;
  baseCurrency: string;
  disabled?: boolean;
}

type NotionalMachine = { state: Accessor<NotionalView> } & NotionalIntents;
type InputChangeEvent = Event & { currentTarget: HTMLInputElement };
type InputKeyDownEvent = KeyboardEvent & { currentTarget: HTMLInputElement };
