// packages/client/src/ui/fx/liveRates/tile/TileRfq.tsx
import { useCallback } from "react";
import {
  type CurrencyPair,
  Direction,
  type Price,
  PriceMovementType,
} from "@rtc/domain";
import type {
  RfqState,
  RfqTileIntents,
} from "../../../../app/presenters/RfqTileMachine";
import { RfqCountdown } from "./RfqCountdown";

/** The machine result the tile passes down: current state plus the RFQ intents. */
export type TileRfqState = { state: RfqState } & RfqTileIntents;

interface TileRfqProps {
  pair: CurrencyPair;
  rfqState: TileRfqState;
  onRequestQuote: () => void;
  onExecute: (direction: Direction, price: Price, notional: number) => void;
  notional: number;
}

function formatPrice(value: number, ratePrecision: number): string {
  return value.toFixed(ratePrecision);
}

export function TileRfq({
  pair,
  rfqState,
  onRequestQuote,
  onExecute,
  notional,
}: TileRfqProps) {
  const { state } = rfqState;

  const handleAccept = useCallback(
    (direction: Direction) => {
      // Capture the quote BEFORE accepting: accept() resets the machine to init
      // and no longer returns the quote synchronously.
      const quote = state.quote;
      rfqState.accept();
      if (!quote) return;
      // Create a synthetic Price to pass to execution
      const syntheticPrice = {
        symbol: pair.symbol,
        bid: quote.bid,
        ask: quote.ask,
        mid: (quote.bid + quote.ask) / 2,
        valueDate: new Date().toISOString().slice(0, 10),
        creationTimestamp: Date.now(),
        movementType: PriceMovementType.NONE,
        spread: "0",
      } satisfies Price;
      onExecute(direction, syntheticPrice, notional);
    },
    [rfqState, state.quote, pair, onExecute, notional],
  );

  if (state.status === "init") {
    return (
      <button
        onClick={onRequestQuote}
        style={{
          padding: "8px 0",
          fontSize: 13,
          fontWeight: 600,
          border: "1px solid var(--accent-primary)",
          borderRadius: 4,
          backgroundColor: "transparent",
          color: "var(--accent-primary)",
          cursor: "pointer",
        }}
      >
        Initiate RFQ
      </button>
    );
  }

  if (state.status === "requested") {
    return (
      <div style={{ display: "flex", flexDirection: "column", gap: 4 }}>
        <div
          style={{
            textAlign: "center",
            fontSize: 12,
            color: "var(--text-muted)",
            padding: "4px 0",
          }}
        >
          Awaiting Price...
        </div>
        <button
          onClick={rfqState.cancel}
          style={{
            padding: "6px 0",
            fontSize: 12,
            border: "1px solid var(--border-primary)",
            borderRadius: 4,
            backgroundColor: "transparent",
            color: "var(--text-secondary)",
            cursor: "pointer",
          }}
        >
          Cancel RFQ
        </button>
      </div>
    );
  }

  if (state.status === "received" && state.quote) {
    return (
      <div style={{ display: "flex", flexDirection: "column", gap: 4 }}>
        <div style={{ display: "flex", gap: 4 }}>
          <button
            onClick={() => handleAccept(Direction.Sell)}
            style={{
              flex: 1,
              padding: "6px 4px",
              fontSize: 12,
              fontWeight: 600,
              border: "1px solid var(--border-primary)",
              borderRadius: 4,
              backgroundColor: "transparent",
              color: "var(--accent-negative)",
              cursor: "pointer",
            }}
          >
            Sell {formatPrice(state.quote.bid, pair.ratePrecision)}
          </button>
          <button
            onClick={() => handleAccept(Direction.Buy)}
            style={{
              flex: 1,
              padding: "6px 4px",
              fontSize: 12,
              fontWeight: 600,
              border: "1px solid var(--border-primary)",
              borderRadius: 4,
              backgroundColor: "transparent",
              color: "var(--accent-positive)",
              cursor: "pointer",
            }}
          >
            Buy {formatPrice(state.quote.ask, pair.ratePrecision)}
          </button>
        </div>
        <RfqCountdown
          remainingMs={state.remainingMs}
          totalMs={state.quote.timeoutMs}
        />
        <button
          onClick={rfqState.reject}
          style={{
            padding: "4px 0",
            fontSize: 11,
            border: "none",
            backgroundColor: "transparent",
            color: "var(--text-muted)",
            cursor: "pointer",
          }}
        >
          Reject
        </button>
      </div>
    );
  }

  if (state.status === "rejected") {
    return (
      <div
        style={{
          textAlign: "center",
          fontSize: 12,
          color: "var(--accent-negative)",
          padding: "8px 0",
        }}
      >
        Quote expired
      </div>
    );
  }

  return null;
}

// packages/client-solid/src/ui/fx/liveRates/tile/TileRfq.tsx
import type { Accessor, JSX } from "solid-js";
import { Match, Switch } from "solid-js";

import type { RfqState, RfqTileIntents } from "@rtc/client-core";
import {
  type CurrencyPair,
  Direction,
  type Price,
  PriceMovementType,
} from "@rtc/domain";

import { RfqCountdown } from "./RfqCountdown";

import styles from "./TileRfq.module.css";

export function TileRfq(props: TileRfqProps): JSX.Element {
  function handleAccept(direction: Direction): void {
    // Capture the quote BEFORE accepting: accept() resets the machine to init
    // and no longer returns the quote synchronously.
    const quote = props.rfqState.state().quote;
    props.rfqState.accept();

    if (!quote) {
      return;
    }

    // Create a synthetic Price to pass to execution
    const syntheticPrice = {
      symbol: props.pair.symbol,
      bid: quote.bid,
      ask: quote.ask,
      mid: (quote.bid + quote.ask) / 2,
      valueDate: new Date().toISOString().slice(0, 10),
      creationTimestamp: Date.now(),
      movementType: PriceMovementType.NONE,
      spread: "0",
    } satisfies Price;
    props.onExecute(direction, syntheticPrice, props.notional);
  }

  // No init branch: the RFQ-initiation affordance is the compact ⚡ RFQ chip
  // in the tile header's pair row (TileHeader), not an extra bottom row.
  return (
    <Switch>
      <Match when={props.rfqState.state().status === "requested"}>
        <div class={styles.requestedWrapper}>
          <div class={styles.awaitingText}>Awaiting Price...</div>
          <button
            type="button"
            onClick={props.rfqState.cancel}
            class={styles.cancelButton}
          >
            Cancel RFQ
          </button>
        </div>
      </Match>
      <Match
        when={
          props.rfqState.state().status === "received" &&
          props.rfqState.state().quote
        }
      >
        <div class={styles.receivedWrapper}>
          <div class={styles.quoteRow}>
            <button
              type="button"
              onClick={() => {
                return handleAccept(Direction.Sell);
              }}
              class={styles.sellQuoteButton}
            >
              Sell{" "}
              {formatPrice(
                props.rfqState.state().quote?.bid ?? 0,
                props.pair.ratePrecision,
              )}
            </button>
            <button
              type="button"
              onClick={() => {
                return handleAccept(Direction.Buy);
              }}
              class={styles.buyQuoteButton}
            >
              Buy{" "}
              {formatPrice(
                props.rfqState.state().quote?.ask ?? 0,
                props.pair.ratePrecision,
              )}
            </button>
          </div>
          <RfqCountdown
            remainingMs={props.rfqState.state().remainingMs}
            totalMs={props.rfqState.state().quote?.timeoutMs ?? 0}
          />
          <button
            type="button"
            onClick={props.rfqState.reject}
            class={styles.rejectButton}
          >
            Reject
          </button>
        </div>
      </Match>
      <Match when={props.rfqState.state().status === "rejected"}>
        <div class={styles.rejectedText}>Quote expired</div>
      </Match>
    </Switch>
  );
}

/** The machine result the tile passes down: current state (accessor,
 * re-emitted fresh per tick) plus the RFQ intents. */
export type TileRfqState = { state: Accessor<RfqState> } & RfqTileIntents;

interface TileRfqProps {
  pair: CurrencyPair;
  rfqState: TileRfqState;
  onExecute: (direction: Direction, price: Price, notional: number) => void;
  notional: number;
}

function formatPrice(value: number, ratePrecision: number): string {
  return value.toFixed(ratePrecision);
}
