// packages/client-solid/src/ui/shell/theme/useTheme.ts
import { useContext } from "solid-js";

import { ThemeContext, type ThemeContextValue } from "./ThemeContext";

export function useTheme(): ThemeContextValue {
  const ctx = useContext(ThemeContext);

  if (!ctx) {
    throw new Error("useTheme must be used within ThemeProvider");
  }

  return ctx;
}

// packages/client-react-native/src/ui/theme/useTheme.ts
// packages/client-react-native/src/ui/theme/useTheme.ts
import { useContext } from "react";

import { ThemeContext } from "#/ui/theme/ThemeContext";
import type { RnTheme } from "#/ui/theme/tokens";

export function useTheme(): RnTheme {
  const theme = useContext(ThemeContext);
  if (theme === null) {
    throw new Error("useTheme must be used within a ThemeProvider");
  }
  return theme;
}
