// packages/client-solid/src/ui/credit/newRfq/DealerChecklist.tsx
import type { JSX } from "solid-js";
import { createMemo, For } from "solid-js";

import { ADAPTIVE_BANK_NAME, type Dealer } from "@rtc/domain";

import styles from "./DealerChecklist.module.css";

// PROTO NewRfq/DealerChecklist.tsx: "All Dealers" master toggle plus one
// checkbox row per dealer. The house dealer (Adaptive Bank) gets a tinted
// name via data-house.
export function DealerChecklist(props: DealerChecklistProps): JSX.Element {
  const allSelected = createMemo((): boolean => {
    return (
      props.dealers.length > 0 &&
      props.dealers.every((dealer) => {
        return props.selectedIds.includes(dealer.id);
      })
    );
  });

  function toggleAllDealers(): void {
    props.onToggleAll();
  }

  function toggleDealer(id: number) {
    return () => {
      props.onToggleDealer(id);
    };
  }

  return (
    <div class={styles.list}>
      <button
        type="button"
        class={styles.row}
        data-testid="new-rfq-dealer-all"
        data-checked={String(allSelected())}
        onClick={toggleAllDealers}
      >
        <CheckBox checked={allSelected()} />
        <span class={styles.name}>All Dealers</span>
      </button>

      <For each={props.dealers}>
        {(dealer: Dealer) => {
          const checked = createMemo((): boolean => {
            return props.selectedIds.includes(dealer.id);
          });

          return (
            <button
              type="button"
              class={styles.row}
              data-testid={`new-rfq-dealer-${dealer.id}`}
              data-checked={String(checked())}
              data-house={String(dealer.name === ADAPTIVE_BANK_NAME)}
              onClick={toggleDealer(dealer.id)}
            >
              <CheckBox checked={checked()} />
              <span class={styles.name}>{dealer.name}</span>
            </button>
          );
        }}
      </For>
    </div>
  );
}

export interface DealerChecklistProps {
  dealers: readonly Dealer[];
  selectedIds: readonly number[];
  onToggleDealer: (id: number) => void;
  onToggleAll: () => void;
}

interface CheckBoxProps {
  checked: boolean;
}

function CheckBox(props: CheckBoxProps): JSX.Element {
  return (
    <span class={styles.box} data-checked={String(props.checked)}>
      {props.checked ? "✓" : ""}
    </span>
  );
}

// packages/client-prototype/src/credit/NewRfq/DealerChecklist.tsx
import type { ReactElement } from "react";

import { DEALERS } from "#/credit/creditData";
import styles from "#/credit/NewRfq/DealerChecklist.module.css";
import type { CreditFormApi } from "#/credit/useCreditForm";

export interface DealerChecklistProps {
  form: CreditFormApi;
}

const HOUSE_DEALER_ID = 1;

// PROTO L552-554: "All Dealers" toggle plus one checkbox row per dealer.
// Dealer id 1 ("Adaptive Bank") is the house dealer — data-house tints it.
export function DealerChecklist(props: DealerChecklistProps): ReactElement {
  const { form } = props;

  return (
    <div className={styles.list}>
      <button
        type="button"
        className={styles.row}
        data-checked={String(form.allDealers)}
        onClick={form.toggleAllDealers}
      >
        <CheckBox checked={form.allDealers} />
        <span className={styles.name}>All Dealers</span>
      </button>

      {DEALERS.map((d) => {
        const checked = form.value.dealerIds.includes(d.id);

        return (
          <button
            key={d.id}
            type="button"
            className={styles.row}
            data-checked={String(checked)}
            data-house={String(d.id === HOUSE_DEALER_ID)}
            onClick={() => {
              form.toggleDealer(d.id);
            }}
          >
            <CheckBox checked={checked} />
            <span className={styles.name}>{d.name}</span>
          </button>
        );
      })}
    </div>
  );
}

interface CheckBoxProps {
  checked: boolean;
}

function CheckBox(props: CheckBoxProps): ReactElement {
  const { checked } = props;

  return (
    <span className={styles.box} data-checked={String(checked)}>
      {checked ? "✓" : ""}
    </span>
  );
}
