// packages/client-solid/src/ui/shell/layout/engine/PanelErrorBoundary.tsx
import type { JSX } from "solid-js";
import { ErrorBoundary } from "solid-js";

import styles from "./PanelErrorBoundary.module.css";

/**
 * Confines one panel's render crash to that panel's own body instead of
 * letting it propagate past InhouseLayoutEngine and unmount the whole app —
 * the net behind the equities-dock crash this was added for in the React
 * client (see the React file's own comment + CandleSeriesPresenter.ts for the
 * other layers of that fix).
 *
 * Solid ships a built-in `ErrorBoundary` (unlike React, which has no hook
 * equivalent and needs a class component): it wraps evaluation of its
 * `children` — which, per Solid's props-as-getters model, only actually runs
 * the wrapped component's body when the getter is read — in a try/catch, so a
 * synchronous render-phase throw from a descendant (`registry[panelId]?.()`
 * in InhouseLayoutEngine.tsx returning `() => <ThrowingPanel/>`, which throws
 * the moment its body runs) is caught here exactly like React's
 * class-boundary catches the analogous render-phase throw.
 */
export function PanelErrorBoundary(
  props: PanelErrorBoundaryProps,
): JSX.Element {
  return (
    <ErrorBoundary
      fallback={() => {
        return (
          <div class={styles.errorState} data-testid="panel-error">
            <span class={styles.errorLabel}>PANEL ERROR</span>
            <span class={styles.errorTitle}>{props.title}</span>
          </div>
        );
      }}
    >
      {props.children}
    </ErrorBoundary>
  );
}

interface PanelErrorBoundaryProps {
  /** The panel's own display title (PanelLeaf already computes this for
   * the header), reused here so the fallback names the same panel a working
   * one would. */
  readonly title: string;
  readonly children: JSX.Element;
}

// packages/client-react/src/ui/shell/layout/engine/PanelErrorBoundary.tsx
import { Component, type ReactNode } from "react";

import styles from "./PanelErrorBoundary.module.css";

interface PanelErrorBoundaryProps {
  /** The panel's own display title (PanelLeaf already computes this for
   * the header), reused here so the fallback names the same panel a working
   * one would. */
  readonly title: string;
  readonly children: ReactNode;
}

interface PanelErrorBoundaryState {
  readonly error: Error | null;
}

/**
 * Confines one panel's render (or effect) crash to that panel's own body
 * instead of letting it propagate past InhouseLayoutEngine and unmount the
 * whole app — the net behind the equities-dock crash this was added for
 * (ChartPanel's first render briefly saw an invalid empty symbol and threw
 * with no boundary anywhere in the tree; see createViewModel.ts and
 * CandleSeriesPresenter.ts for the other two layers of that fix).
 *
 * A class component is the only React primitive that can implement this
 * (there is no hook equivalent as of React 19) — the sanctioned exception to
 * this codebase's function-component convention; see
 * `rtc/class-filename-match` and `max-classes-per-file` in eslint.config.mjs.
 *
 * React's error-boundary mechanism catches errors thrown during a
 * descendant's render AND its passive effects (the latter is exactly how the
 * equities crash actually surfaced: react-rxjs's `bind()` re-throws a stream
 * error via a state-updater function invoked on the next render), so wrapping
 * `registry[panelId]?.()` in InhouseLayoutEngine.tsx is sufficient — no
 * effect-specific handling needed here.
 */
export class PanelErrorBoundary extends Component<
  PanelErrorBoundaryProps,
  PanelErrorBoundaryState
> {
  state: PanelErrorBoundaryState = { error: null };

  static getDerivedStateFromError(error: unknown): PanelErrorBoundaryState {
    return {
      error: error instanceof Error ? error : new Error(String(error)),
    };
  }

  render(): ReactNode {
    const { error } = this.state;

    if (!error) {
      return this.props.children;
    }

    return (
      <div className={styles.errorState} data-testid="panel-error">
        <span className={styles.errorLabel}>PANEL ERROR</span>
        <span className={styles.errorTitle}>{this.props.title}</span>
      </div>
    );
  }
}
