// packages/client-react/src/ui/App.tsx
import { lazy, type ReactElement, Suspense } from "react";

import { PANEL_SPECS, visibleRootOf } from "@rtc/client-core";
import { useViewModel } from "@rtc/react-bindings";

import { CreditViewProvider } from "./credit/CreditViewProvider";
import { FxViewProvider } from "./fx/FxViewProvider";
import { AmbientBackground } from "./shell/background/AmbientBackground";
import { HeaderChrome, type WorkspaceTab } from "./shell/chrome/HeaderChrome";
import { ConnectionOverlay } from "./shell/connection/ConnectionOverlay";
import { JarvisOverlay } from "./shell/jarvis/JarvisOverlay";
import { JarvisPanelLayer } from "./shell/jarvis/panels/JarvisPanelLayer";
import { useJarvisDrivenPulse } from "./shell/jarvis/useJarvisDrivenPulse";
import {
  appHeadRegistry,
  dockedHeadsFor,
} from "./shell/layout/engine/appHeadRegistry";
import {
  appPanelRegistry,
  dockedRegistryFor,
  dockedSpecsFor,
} from "./shell/layout/engine/appPanelRegistry";
import { InhouseLayoutEngine } from "./shell/layout/engine/InhouseLayoutEngine";
import { LockScreen } from "./shell/lock/LockScreen";
import { StatusBar } from "./shell/status/StatusBar";

import styles from "./App.module.css";
import drivenPulseStyles from "./shell/jarvis/DrivenPulse.module.css";

export function App(): ReactElement {
  // Machine-backed nav (Task 10): the promoted composition-root singleton
  // (Presenters.workspaceNav) replacing the useState<WorkspaceTab> that used
  // to live here — reachable now from Jarvis's drive-the-app "switchTab"
  // command too. `key={activeTab}` below is unchanged: WorkspaceEngine still
  // remounts per tab, but the underlying layout machines now survive that
  // remount (see Presenters.layoutFor's doc).
  const { useWorkspaceNav } = useViewModel();
  const { state: navState, switchTab } = useWorkspaceNav();
  const activeTab = navState.activeTab;
  const { pulsing, clearPulse } = useJarvisDrivenPulse();

  return (
    <div className={styles.app}>
      <AmbientBackground />
      <HeaderChrome activeTab={activeTab} onTabChange={switchTab} />
      <div
        data-jarvis-driven={pulsing ? "true" : "false"}
        className={
          pulsing
            ? `${styles.workspaceRegion} ${drivenPulseStyles.driven}`
            : styles.workspaceRegion
        }
        onAnimationEnd={clearPulse}
      >
        <WorkspaceEngine key={activeTab} tab={activeTab} />
      </div>
      <StatusBar />
      <ConnectionOverlay />
      <LockScreen />
      <JarvisOverlay />
      <JarvisPanelLayer />
    </div>
  );
}

interface WorkspaceEngineProps {
  tab: WorkspaceTab;
}

// Lazy: dockview + its CSS is ~75KB gzip, but the default in-house engine
// serves ~100% of users — split it into its own chunk instead of shipping
// it to everyone.
const DockviewLayoutEngine = lazy(() => {
  return import("./shell/layout/dockview/DockviewLayoutEngine").then((m) => {
    return { default: m.DockviewLayoutEngine };
  });
});

function WorkspaceEngine({ tab }: WorkspaceEngineProps): ReactElement {
  const { useLayout, useJarvisPanels, useLayoutEngine, useDockLayoutStore } =
    useViewModel();
  const { state, maximize, restore, collapse, expand, resize } = useLayout(tab);
  // The in-house engine renders the VISIBLE projection: View-menu-closed
  // leaves are pruned from the tree it sees (visibleRootOf is referentially
  // stable when nothing is closed). The Dockview branch keeps the raw state
  // fields — its projection is the bridge's closed-set replay.
  const visibleState = {
    ...state,
    root: visibleRootOf(state.root, state.closed),
  };
  // Docked desk panels render as leaves inside THIS engine (not the
  // floating JarvisPanelLayer, which renders floatingPanels only) — merged
  // on top of the static app registries so a dock/undock or a live spec
  // edit ("make it a table" while docked) is reflected on the very next
  // render, regardless of which tab the panel was docked into.
  const { dockedPanels, undockPanel, dismissPanel } = useJarvisPanels();
  const registry = { ...appPanelRegistry, ...dockedRegistryFor(dockedPanels) };
  const specs = { ...PANEL_SPECS, ...dockedSpecsFor(dockedPanels) };
  const headRegistry = {
    ...appHeadRegistry,
    ...dockedHeadsFor(dockedPanels, undockPanel, dismissPanel),
  };
  const { engine } = useLayoutEngine();
  const dockLayoutStore = useDockLayoutStore();
  return (
    <FxViewProvider>
      <CreditViewProvider>
        {engine === "dockview" ? (
          <Suspense fallback={null}>
            {/* Same merged registries as the in-house branch: dockview looks
                a docked panel's body/head/spec up by id exactly as the
                in-house engine does. Its SEED tree is still the static
                default (createDefaultLayoutPort), so a pinned panel only
                surfaces here once its id is in the persisted blob — docking
                a Jarvis panel INTO dockview is not wired this round. */}
            <DockviewLayoutEngine
              tab={tab}
              registry={registry}
              specs={specs}
              headRegistry={headRegistry}
              store={dockLayoutStore}
              maximized={state.maximized}
              collapsed={state.collapsed}
              closed={state.closed}
              onMaximize={maximize}
              onRestore={restore}
              onCollapse={collapse}
              onExpand={expand}
            />
          </Suspense>
        ) : (
          <InhouseLayoutEngine
            state={visibleState}
            registry={registry}
            specs={specs}
            headRegistry={headRegistry}
            onMaximize={maximize}
            onRestore={restore}
            onCollapse={collapse}
            onExpand={expand}
            onResize={resize}
          />
        )}
      </CreditViewProvider>
    </FxViewProvider>
  );
}

// packages/client-solid/src/ui/App.tsx
import type { JSX } from "solid-js";
import { lazy, Show, Suspense } from "solid-js";

import { useViewModel } from "@rtc/solid-bindings";

import { CreditViewProvider } from "#/ui/credit/CreditViewProvider";
import { FxViewProvider } from "#/ui/fx/FxViewProvider";

import { AmbientBackground } from "./shell/background/AmbientBackground";
import { HeaderChrome, type WorkspaceTab } from "./shell/chrome/HeaderChrome";
import { ConnectionOverlay } from "./shell/connection/ConnectionOverlay";
import { JarvisOverlay } from "./shell/jarvis/JarvisOverlay";
import { JarvisPanelLayer } from "./shell/jarvis/panels/JarvisPanelLayer";
import { useJarvisDrivenPulse } from "./shell/jarvis/useJarvisDrivenPulse";
import { appHeadRegistry } from "./shell/layout/engine/appHeadRegistry";
import { appPanelRegistry } from "./shell/layout/engine/appPanelRegistry";
import { InhouseLayoutEngine } from "./shell/layout/engine/InhouseLayoutEngine";
import { LockScreen } from "./shell/lock/LockScreen";
import { StatusBar } from "./shell/status/StatusBar";

import styles from "./App.module.css";
import drivenPulseStyles from "./shell/jarvis/DrivenPulse.module.css";

/** Shell chrome wired to the real ViewModel (Task 9 — theme/chrome/boot/lock)
 * plus one shared WorkspaceEngine serving every tab's live layout engine and
 * panel subtree: FX (Tasks 10/13), Credit (Task 14), Equities (Task 15), and
 * Admin (Task 16), all through the SAME `appPanelRegistry`/`appHeadRegistry`,
 * keyed by panel id — the exact structure of the react `App.tsx`. */
export function App(): JSX.Element {
  // Machine-backed nav (Task 10/11 parity): the promoted composition-root
  // singleton (Presenters.workspaceNav) replacing the createSignal<WorkspaceTab>
  // that used to live here — reachable now from Jarvis's drive-the-app
  // "switchTab" command too. The keyed `<Show>` below is unchanged:
  // WorkspaceEngine still remounts per tab, but the underlying layout
  // machines now survive that remount (see Presenters.layoutFor's doc).
  const { useWorkspaceNav } = useViewModel();
  const { state: navState, switchTab } = useWorkspaceNav();
  const pulse = useJarvisDrivenPulse();

  return (
    <div class={styles.app}>
      <AmbientBackground />
      <HeaderChrome activeTab={navState().activeTab} onTabChange={switchTab} />
      <div
        ref={pulse.ref}
        data-jarvis-driven={pulse.pulsing() ? "true" : "false"}
        class={
          pulse.pulsing()
            ? `${styles.workspaceRegion} ${drivenPulseStyles.driven}`
            : styles.workspaceRegion
        }
      >
        <Show when={navState().activeTab} keyed>
          {(tab: WorkspaceTab) => {
            return <WorkspaceEngine tab={tab} />;
          }}
        </Show>
      </div>
      <StatusBar />
      <ConnectionOverlay />
      <LockScreen />
      <JarvisOverlay />
      <JarvisPanelLayer />
    </div>
  );
}

interface WorkspaceEngineProps {
  tab: WorkspaceTab;
}

// Lazy: dockview + its CSS is ~75KB gzip, but the default in-house engine
// serves ~100% of users — split it into its own chunk instead of shipping
// it to everyone.
const DockviewLayoutEngine = lazy(() => {
  return import("./shell/layout/dockview/DockviewLayoutEngine").then((m) => {
    return { default: m.DockviewLayoutEngine };
  });
});

/** Owns the active tab's `useLayout(tab)` machine and nests BOTH domain
 * view-context seams (`FxViewProvider` → `CreditViewProvider`), mirroring the
 * react `App.tsx`'s single `WorkspaceEngine` that serves all tabs from one
 * component. The keyed `<Show>` in `App` is the Solid-native equivalent of
 * the react original's `key={activeTab}` forced remount: switching tabs
 * genuinely unmounts this component and mounts a fresh one for the new tab
 * — which is also why reading `props.tab` once at setup is intentional here:
 * the component can never see a different tab within one lifetime.
 * `useLayout(tab)` no longer disposes anything on that unmount (Task 10/11):
 * `machines.layout(tab)` resolves to a composition-root SINGLETON per tab
 * (`Presenters.layoutFor`), read directly via `toSignal`, so layout state
 * (maximized/collapsed/split sizes) SURVIVES this remount instead of
 * resetting — a driven "layout" DriveCommand's target stays the same
 * instance the mounted view reads from either way. */
function WorkspaceEngine(props: WorkspaceEngineProps): JSX.Element {
  const { useLayout, useLayoutEngine, useDockLayoutStore } = useViewModel();
  const { state, maximize, restore, collapse, expand, resize } = useLayout(
    // eslint-disable-next-line solid/reactivity -- setup-scope read is correct under the keyed-<Show> remount (see doc comment)
    props.tab,
  );
  const { engine } = useLayoutEngine();
  const dockLayoutStore = useDockLayoutStore();

  return (
    <FxViewProvider>
      <CreditViewProvider>
        <Show
          when={engine() === "dockview"}
          fallback={
            <InhouseLayoutEngine
              state={state()}
              registry={appPanelRegistry}
              headRegistry={appHeadRegistry}
              onMaximize={maximize}
              onRestore={restore}
              onCollapse={collapse}
              onExpand={expand}
              onResize={resize}
            />
          }
        >
          <Suspense fallback={null}>
            <DockviewLayoutEngine
              tab={props.tab}
              registry={appPanelRegistry}
              headRegistry={appHeadRegistry}
              store={dockLayoutStore}
              maximized={state().maximized}
            />
          </Suspense>
        </Show>
      </CreditViewProvider>
    </FxViewProvider>
  );
}
