// packages/client-solid/src/ui/admin/kpis/KpiCard.tsx
import type { JSX } from "solid-js";

import type { AdminKpiVm } from "@rtc/client-core";

import { KpiSparkline } from "./KpiSparkline";

import styles from "./KpiRow.module.css";

/**
 * One KPI card — label, glowing value + unit, trend delta, and a bottom
 * sparkline. Colour state is carried on data-* attributes; CSS colours it.
 * PROTO Kpis/KpiCard.tsx.
 */
export function KpiCard(props: KpiCardProps): JSX.Element {
  return (
    <div data-testid={`admin-kpi-${props.kpi.key}`} class={styles.card}>
      <div class={styles.label}>{props.kpi.label}</div>
      <div class={styles.valueRow}>
        <span
          class={styles.value}
          data-kpi={props.kpi.key}
          data-warn={String(props.kpi.warn)}
        >
          {props.kpi.value}
        </span>
        <span class={styles.unit}>{props.kpi.unit}</span>
      </div>
      <div class={styles.delta} data-delta-up={String(props.kpi.deltaUp)}>
        {props.kpi.delta}
      </div>
      <KpiSparkline kpi={props.kpi} />
    </div>
  );
}

export interface KpiCardProps {
  kpi: AdminKpiVm;
}

// packages/client-prototype/src/admin/Kpis/KpiCard.tsx
import type { ReactElement } from "react";

import styles from "#/admin/Kpis/KpiRow.module.css";
import { KpiSparkline } from "#/admin/Kpis/KpiSparkline";
import type { AdminKpi } from "#/admin/types";

export interface KpiCardProps {
  kpi: AdminKpi;
}

// PROTO L687-696: one KPI card — label, glowing value + unit, trend delta, and a
// bottom sparkline. Colour state is carried on data-* attributes (CSS colours it).
export function KpiCard(props: KpiCardProps): ReactElement {
  const { kpi } = props;

  return (
    <div className={styles.card}>
      <div className={styles.label}>{kpi.label}</div>
      <div className={styles.valueRow}>
        <span
          className={styles.value}
          data-kpi={kpi.key}
          data-warn={String(kpi.warn)}
        >
          {kpi.value}
        </span>
        <span className={styles.unit}>{kpi.unit}</span>
      </div>
      <div className={styles.delta} data-delta-up={String(kpi.deltaUp)}>
        {kpi.delta}
      </div>
      <KpiSparkline kpi={kpi} />
    </div>
  );
}
