// packages/client-solid/src/ui/equities/chart/CandleBars.tsx
import { For, type JSX } from "solid-js";

import type { ChartVm } from "@rtc/motion-core";

import styles from "./CandleBars.module.css";

/**
 * One wick + body span per candle. All geometry rides in via the
 * `--x/--top/--h/--w/--w*` custom properties precomputed by chartVm — each
 * `style={...}` here references that precomputed value (not an inline object
 * literal), so it needs no lint escape hatch. Up/down colour is a `data-up`
 * hook; the last candle also carries `data-last` (full opacity) and
 * `data-glow` (a brief box-shadow while the price is actively ticking).
 */
export function CandleBars(props: CandleBarsProps): JSX.Element {
  return (
    <For each={props.candles}>
      {(cd: ChartVm["candles"][number]): JSX.Element => {
        return (
          <div data-candle="" data-up={String(cd.up)}>
            <span
              class={styles.wick}
              style={cd.wickStyle}
              data-up={String(cd.up)}
            />
            <span
              class={styles.body}
              style={cd.style}
              data-up={String(cd.up)}
              data-last={String(cd.last)}
              data-glow={String(cd.glow)}
            />
          </div>
        );
      }}
    </For>
  );
}

export interface CandleBarsProps {
  candles: ChartVm["candles"];
}

// packages/client-prototype/src/equities/Chart/CandleBars.tsx
import type { ReactElement } from "react";

import styles from "#/equities/Chart/CandleBars.module.css";
import type { ChartVm } from "#/equities/chartVm";

export interface CandleBarsProps {
  candles: ChartVm["candles"];
}

// PROTO L1343: one wick + body div per candle. All geometry rides in via the
// `--x/--top/--h/--w/--w*` custom properties on each element (the sanctioned
// inline-style escape hatch); up/down colour is a `data-up` class hook.
export function CandleBars(props: CandleBarsProps): ReactElement {
  const { candles } = props;

  return (
    <>
      {candles.map((cd) => {
        return (
          <div key={cd.key} data-candle="" data-up={String(cd.up)}>
            <span
              className={styles.wick}
              style={cd.wickStyle}
              data-up={String(cd.up)}
            />
            <span
              className={styles.body}
              style={cd.style}
              data-up={String(cd.up)}
              data-last={String(cd.last)}
              data-glow={String(cd.glow)}
            />
          </div>
        );
      })}
    </>
  );
}
