// packages/client-solid/src/ui/equities/chart/TimeframePills.tsx
import { For, type JSX } from "solid-js";

import type { CandleTimeframe } from "@rtc/domain";

import styles from "./TimeframePills.module.css";

/** The 1D/1W/1M/3M timeframe selector. Pure props leaf: `tf` is the current
 * selection, `onSet` fires when a pill is clicked. */
export function TimeframePills(props: TimeframePillsProps): JSX.Element {
  function selectTimeframe(id: CandleTimeframe) {
    return () => {
      props.onSet(id);
    };
  }

  return (
    <div class={styles.pills}>
      <For each={TIMEFRAMES}>
        {(id: CandleTimeframe): JSX.Element => {
          return (
            <button
              type="button"
              class={styles.pill}
              data-tf={id}
              data-active={String(id === props.tf)}
              onClick={selectTimeframe(id)}
            >
              {id}
            </button>
          );
        }}
      </For>
    </div>
  );
}

const TIMEFRAMES: readonly CandleTimeframe[] = ["1D", "1W", "1M", "3M"];

export interface TimeframePillsProps {
  tf: CandleTimeframe;
  onSet: (tf: CandleTimeframe) => void;
}

// packages/client-prototype/src/equities/Chart/TimeframePills.tsx
import type { ReactElement } from "react";

import styles from "#/equities/Chart/TimeframePills.module.css";
import type { Timeframe } from "#/equities/types";

export interface TimeframePillsProps {
  tf: Timeframe;
  onSet: (tf: Timeframe) => void;
}

const TIMEFRAMES: Timeframe[] = ["1D", "1W", "1M", "3M"];

// PROTO L603: the 1D/1W/1M/3M timeframe selector.
export function TimeframePills(props: TimeframePillsProps): ReactElement {
  const { tf, onSet } = props;

  return (
    <div className={styles.pills}>
      {TIMEFRAMES.map((id) => {
        return (
          <TimeframePill key={id} id={id} active={id === tf} onSet={onSet} />
        );
      })}
    </div>
  );
}

interface TimeframePillProps {
  id: Timeframe;
  active: boolean;
  onSet: (tf: Timeframe) => void;
}

function TimeframePill(props: TimeframePillProps): ReactElement {
  const { id, active, onSet } = props;

  function selectTimeframe(): void {
    onSet(id);
  }

  return (
    <button
      type="button"
      className={styles.pill}
      data-tf={id}
      data-active={String(active)}
      onClick={selectTimeframe}
    >
      {id}
    </button>
  );
}
