// packages/client-solid/src/ui/fx/blotter/columnFilter/SetFilter.tsx
import type { JSX } from "solid-js";
import { createSignal, For } from "solid-js";

import type { ColumnFilter } from "@rtc/client-core";

import styles from "./SetFilter.module.css";

export function SetFilter<TRow>(props: SetFilterProps<TRow>): JSX.Element {
  const valSet = new Set<string>();

  for (const row of props.rows) {
    valSet.add(String(row[props.column]));
  }

  const allValues = [...valSet].sort();

  const [selected, setSelected] = createSignal<Set<string>>(
    props.currentFilter?.type === "set"
      ? new Set(props.currentFilter.values)
      : new Set(allValues),
  );

  function toggleValue(val: string): void {
    setSelected((prev) => {
      const next = new Set(prev);

      if (next.has(val)) {
        next.delete(val);
      } else {
        next.add(val);
      }

      return next;
    });
  }

  function handleApply(): void {
    if (selected().size === allValues.length) {
      props.onApply(null); // all selected = no filter
    } else {
      props.onApply({ type: "set", column: props.column, values: selected() });
    }
  }

  return (
    <div class={styles.container}>
      <For each={allValues}>
        {(val: string) => {
          return (
            <label class={styles.option}>
              <input
                type="checkbox"
                data-testid={`set-filter-option-${val}`}
                checked={selected().has(val)}
                onChange={() => {
                  toggleValue(val);
                }}
              />
              {val}
            </label>
          );
        }}
      </For>
      <button
        type="button"
        data-testid="set-filter-apply"
        onClick={handleApply}
        class={styles.applyBtn}
      >
        Apply
      </button>
    </div>
  );
}

interface SetFilterProps<TRow> {
  column: keyof TRow;
  rows: readonly TRow[];
  currentFilter: ColumnFilter<TRow> | undefined;
  onApply: (filter: ColumnFilter<TRow> | null) => void;
}

// packages/client/src/blotter/columnFilter/SetFilter.tsx
import { useCallback, useMemo, useState } from "react";
import type { Trade } from "@rtc/domain";
import type { ColumnFilter } from "./filterState";

interface SetFilterProps {
  column: keyof Trade;
  trades: readonly Trade[];
  currentFilter: ColumnFilter | undefined;
  onApply: (filter: ColumnFilter | null) => void;
}

export function SetFilter({ column, trades, currentFilter, onApply }: SetFilterProps) {
  const allValues = useMemo(() => {
    const vals = new Set<string>();
    for (const trade of trades) vals.add(String(trade[column]));
    return [...vals].sort();
  }, [trades, column]);

  const [selected, setSelected] = useState<Set<string>>(() => {
    if (currentFilter?.type === "set") return new Set(currentFilter.values);
    return new Set(allValues);
  });

  const toggleValue = useCallback((val: string) => {
    setSelected((prev) => {
      const next = new Set(prev);
      if (next.has(val)) next.delete(val);
      else next.add(val);
      return next;
    });
  }, []);

  const handleApply = useCallback(() => {
    if (selected.size === allValues.length) {
      onApply(null); // all selected = no filter
    } else {
      onApply({ type: "set", column, values: selected });
    }
  }, [selected, allValues.length, onApply, column]);

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 4, padding: 8 }}>
      {allValues.map((val) => (
        <label key={val} style={{ display: "flex", alignItems: "center", gap: 4, fontSize: 12, color: "var(--text-primary)", cursor: "pointer" }}>
          <input
            type="checkbox"
            checked={selected.has(val)}
            onChange={() => toggleValue(val)}
          />
          {val}
        </label>
      ))}
      <button
        onClick={handleApply}
        style={{
          marginTop: 4,
          padding: "4px 8px",
          fontSize: 11,
          border: "1px solid var(--border-primary)",
          borderRadius: 3,
          backgroundColor: "var(--accent-primary)",
          color: "#fff",
          cursor: "pointer",
        }}
      >
        Apply
      </button>
    </div>
  );
}
