// packages/client-solid/src/ui/credit/rfqs/QuoteRow.tsx
import type { JSX } from "solid-js";
import { Show } from "solid-js";

import type { QuoteVm } from "./rfqCardVm";

import styles from "./QuoteRow.module.css";

/** PROTO Rfqs/QuoteRow.tsx: one dealer's quote line inside an RfqCard — a ★
 * when it's the best live price, the dealer name (house dealer tinted), the
 * price text, and an ACCEPT button while the quote is still live and priced. */
export function QuoteRow(props: QuoteRowProps): JSX.Element {
  return (
    <div
      class={styles.row}
      data-state={props.vm.state}
      data-best={String(props.vm.best)}
      data-house={String(props.vm.house)}
      data-testid={`rfq-quote-${props.vm.quoteId}`}
    >
      <div class={styles.name}>
        <Show when={props.vm.best}>
          <span class={styles.star}>★</span>
        </Show>
        <span
          class={styles.bank}
          data-house={String(props.vm.house)}
          data-testid={`rfq-quote-bank-${props.vm.quoteId}`}
        >
          {props.vm.bank}
        </span>
      </div>
      <div class={styles.priceWrap}>
        <span
          class={styles.price}
          data-state={props.vm.state}
          data-best={String(props.vm.best)}
        >
          {props.vm.priceText}
        </span>
        <Show when={props.vm.canAccept}>
          <button
            type="button"
            class={styles.acceptBtn}
            data-best={String(props.vm.best)}
            data-testid={`rfq-quote-accept-${props.vm.quoteId}`}
            onClick={props.onAccept}
          >
            ACCEPT
          </button>
        </Show>
      </div>
    </div>
  );
}

export interface QuoteRowProps {
  vm: QuoteVm;
  onAccept: () => void;
}

// packages/client-prototype/src/credit/Rfqs/QuoteRow.tsx
import type { ReactElement } from "react";

import styles from "#/credit/Rfqs/QuoteRow.module.css";
import type { QuoteVm } from "#/credit/rfqCardVm";

export interface QuoteRowProps {
  vm: QuoteVm;
  onAccept: () => void;
}

// PROTO L572: one dealer's quote line inside an RfqCard — a ★ when it's the
// best live price, the dealer name (house dealer tinted), the price text,
// and an ACCEPT button while the quote is still live and priced.
export function QuoteRow(props: QuoteRowProps): ReactElement {
  const { vm, onAccept } = props;

  return (
    <div className={styles.row} data-state={vm.state}>
      <div className={styles.name}>
        {vm.best ? <span className={styles.star}>★</span> : null}
        <span className={styles.bank} data-house={String(vm.house)}>
          {vm.bank}
        </span>
      </div>
      <div className={styles.priceWrap}>
        <span
          className={styles.price}
          data-state={vm.state}
          data-best={String(vm.best)}
        >
          {vm.priceText}
        </span>
        {vm.canAccept ? (
          <button
            type="button"
            className={styles.acceptBtn}
            data-best={String(vm.best)}
            onClick={onAccept}
          >
            ACCEPT
          </button>
        ) : null}
      </div>
    </div>
  );
}
